### PR TITLE
Update metrics.md

### PR DESCRIPTION
**Pull request by callum-mcdata**
There were incorrect required fields that I updated. Expression is required but time_grains is optional.

### CODE REVIEW

**Comment by mirnawong1** [comment]
looking at this now for you @callum-mcdata !

**Review by mirnawong1 — APPROVED** [review]
approved @callum-mcdata and deploy looks good. just wanted to note that time_grains is not required for v1.4, however, it is required for v1.3 and older.

**Comment by callum-mcdata** [comment]
@mirnawong1 that is confirmed.

**Comment by mirnawong1** [comment]
shipping this for you @callum-mcdata !

**Pull request merged**
