### PR TITLE
Update set.md

### PR DESCRIPTION
**Pull request by ameerulislam**
## What are you changing in this pull request and why?

Added string example, It needs a single quote inside the double quote. to read a string. Otherwise, it was giving compilation error. Set is heavily used as a variable alternative.

## Checklist
- [x] I have reviewed the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) so my content adheres to these guidelines.
- [x] The topic I'm writing about is for specific dbt version(s) and I have versioned it according to the [version a whole page](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) and/or [version a block of content](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#versioning-blocks-of-content) guidelines.
- [x] I have added checklist item(s) to this list for anything anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

### CODE REVIEW

**Review by mirnawong1 — APPROVED** [review]
hey @ameerulislam , thank you for opening up this pr to enhance this section! going to merge this for you and looking forward to future contributions ✨

**Comment by ameerulislam** [comment]
Alhamdulillah!!! this is a huge moment for me. I always wanted to contribute to open source and recently dbt has been my top choice. As I love this software so much. You just boosted my confidence, big time. 
Thank You!

**Comment by ameerulislam** [comment]
Hi @mirnawong1 , I'm confused about one thing though. Why am I not shown as one of the contributors of the original repo after this PR merge?

**Comment by mirnawong1** [comment]
hey @ameerulislam , oh can you tell me where you're looking so i can investigate?

**Comment by ameerulislam** [comment]
Here 
https://github.com/dbt-labs/docs.getdbt.com/graphs/contributors?from=31%2F08%2F2024
with the period of last month. I thought I'll be present there but I'm not in there.

**Comment by mirnawong1** [comment]
hey @ameerulislam thanks for sharing! oh, so sorry but i think this may be the way GitHub presents information, unfortunately. if you look at the top of the page, it says:

> Contributions per week to current, line counts have been omitted because commit count exceeds 10,000.

which means if it _didn't_ omit it, you'd probably show up in the 'per week' category? 

or it could be related to the reasons listed [here](https://docs.github.com/en/repositories/viewing-activity-and-data-for-your-repository/viewing-a-projects-contributors#troubleshooting-contributors)  too.  but the good thing is that your great docs contributions should certainly contribute to your contributions graph in your own personal profile page:

Screenshot 2024-10-02 at 14 18 37

**Pull request merged**
