### PR TITLE
change favicon to not conflict with autogenerated docs

### PR DESCRIPTION
**Pull request by jasnonaz**
## Description & motivation
We have consistently heard feedback from users that the orange favicon being the same on this site as in [dbt Docs](https://github.com/dbt-labs/dbt-docs). This PR updates to a navy version of the favicon - with the potential to shift to another dbt Labs color once we consult with the design team.

### CODE REVIEW

**Review by runleonarun — COMMENTED** [review]
@jasnonaz I love this and am OK with you shipping as is, but in my particular browser tab, I can't see the favicon:
Screen Shot 2022-10-12 at 10 49 36 AM

**Review by joellabes — APPROVED** [review]
y e s.

Navy isn't perfect for dark mode but GitHub's icon isn't either, i think we can clean this up as a fast-follow unless we manage to get something nicer before then! 

people are gonna flip. High risk move to release this and let it overshadow the entire rest of developer hub 😰

**Comment by jasnonaz** [comment]
Lavendar option via @joellabes 
image

**Comment by jasnonaz** [comment]
Tremendous thanks to Kevin Jackson and the Design team for fulfilling this 11th hour request and giving us a sweet new on brand favicon 🙏  🙏

**Pull request merged**
