### PR TITLE
added a new image for the groups & licenses page

### PR DESCRIPTION
**Pull request by Tonayya**
## What are you changing in this pull request and why?
added a new image for the groups & licenses page, as this no longer leaves under a "Team" subgroup in the UI.
## Checklist
- [x] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) so my content adheres to these guidelines.

### CODE REVIEW

**Comment by mirnawong1** [comment]
hey @Tonayya nice catch! this is for this page right: https://docs.getdbt.com/docs/cloud/manage-access/about-user-access#groups?

**Comment by Tonayya** [comment]
Hey @mirnawong1 yep! I'm just committing the changes there too but I had to first upload the new image for it :D

**Comment by mirnawong1** [comment]
ah amazing, ok will hang tight and thanks again! just gimme a tag and I'll get this over for you ✨

**Review by mirnawong1 — APPROVED** [review]
🚢

**Pull request merged**
