### PR TITLE
add pagination and styles

### PR DESCRIPTION
**Pull request by JKarlavige**
## What are you changing in this pull request and why?

This adds pagination for the `DocCarousel` component.

[Asana](https://app.asana.com/0/1200099998847559/1204787966212993/f)

## Preview
Carousel is used on the page below:
https://deploy-preview-3610--docs-getdbt-com.netlify.app/docs/cloud/dbt-cloud-ide/lint-format

### CODE REVIEW

**Review by john-rock — APPROVED** [review]
lgtm!

**Review by lfracalossiFA — APPROVED** [review]
lgtm!

**Comment by mirnawong1** [comment]
love it, thank you all!

**Comment by lfracalossiFA** [comment]
Since Jason is out this week, I'll go ahead and merge this PR for him.

**Pull request merged**
