### PR TITLE
Updates dbt logo with trademark and add trademark to focus areas

### PR DESCRIPTION
**Pull request by JKarlavige**
## Description & motivation
This updates the dbt logo to include the trademark symbol, and adds the trademark to a few focus areas on the homepage and in the navigation areas.

## Pre-release docs
Is this change related to an unreleased version of dbt?
- [ ] Yes: please
    - update the base branch to `next`
    - add Changelog components: `<Changelog>[New/Changed] in v0.x.0</Changelog>`
    - add links to the "New and changed documentation" section of the latest [Migration Guide](../website/docs/docs/guides/migration-guide)
- [x] No: please ensure the base branch is `current`
- [ ] Unsure: we'll let you know!

### CODE REVIEW

**Comment by lfracalossiFA** [comment]
Hm. From a technical perspective, this all looks good, but I'm wondering if the (TM) is making it look bit too intrusively corporate? @annafil @runleonarun do you have any thoughts on this?

**Comment by JKarlavige** [comment]
> Hm. From a technical perspective, this all looks good, but I'm wondering if the (TM) is making it look bit too intrusively corporate? @annafil @runleonarun do you have any thoughts on this?

This is my concern as well for this task in general. Looking at larger corporate companies (Microsoft, Apple) I don't see the trademark icon used anywhere within the content.

**Review by lfracalossiFA — APPROVED** [review]

**Review by runleonarun — APPROVED** [review]
LGTM

**Comment by lfracalossiFA** [comment]
Seems like no one saw any issues with this when I posted it on the Slack, so you are good to merge!

**Pull request merged**
