### PR TITLE
Fix typo in dbt tests documentation page

### PR DESCRIPTION
**Pull request by martsec**
## Description & motivation

Fix a typo found in the DBT docs tests page https://docs.getdbt.com/reference/resource-properties/tests

### CODE REVIEW

**Review by nghi-ly — APPROVED** [review]
@martsec : thanks so much for catching this! :shipit:

**Comment by martsec** [comment]
Welcome!  Do I merge it? Or you have to do it?

**Comment by nghi-ly** [comment]
thanks for the warm welcome! you can go ahead and merge it, @martsec .

**Comment by martsec** [comment]
Ah, It seems I cannot merge since I don't have write access

**Comment by nghi-ly** [comment]
my utmost apologies, @martsec! merging now

**Pull request merged**
