### PR TITLE
Remove beta callout

### PR DESCRIPTION
**Pull request by nghi-ly**
## What are you changing in this pull request and why?

- [x] Remove beta callout from:
 https://docs.getdbt.com/docs/deploy/deploy-environments#set-as-production-environment-beta 
- [x] Remove partial file as part of cleanup since this page ^ is the only one using it

## Checklist
- [x] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) and [About versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) so my content adheres to these guidelines.

Removing or renaming existing pages (delete if not applicable):
- ~~[ ] Remove page from `website/sidebars.js`~~ n/a to partial file
- ~~[ ] Add an entry `website/static/_redirects`~~ n/a to partial file

### CODE REVIEW

**Review by joellabes — APPROVED** [review]
This lgtm! One change before merging: There are [four places](https://github.com/search?q=repo%3Adbt-labs%2Fdocs.getdbt.com%20%23set-as-production-environment-beta&type=code) that depend on the old anchor (`#set-as-production-environment-beta`)

Can you update those to the new anchor too? in future it's probably worth us setting a [custom heading ID](https://docusaurus.io/docs/next/markdown-features/toc#heading-ids) when we have beta functionality, so that it keeps working post-launch. (I'll go mention this in the product docs channel!)

**Comment by nghi-ly** [comment]
thank you, @joellabes , for flagging! weird,  i would've expected that be caught by our link checker.

**Comment by joellabes** [comment]
> i would've expected that would've been caught by our link checker.

That only checks that the page loads correctly - people will be dropped at the top of the page but it still _exists_ so it passes

**Comment by nghi-ly** [comment]
@joellabes : ah that's right, it's not a 404. fixed the links, thanks!

**Pull request merged**
