### PR TITLE
Fix flash of 404 on certain pages

### PR DESCRIPTION
**Pull request by john-rock**
## What are you changing in this pull request and why?
This PR replaces all instances of directories with capitalized letters with lowercase letters. Vercel does not like capitalized letters for directories that are built as page routes. 

Going forward we should not use capitalization in directories or files.

On the live site this page will show a flash of 404 before the page loads. Note that on the live site the current directory name for this page is Sept-2023.
https://docs.getdbt.com/docs/dbt-versions/release-notes/sept-2023/product-docs-summer

In this PR I've removed the capitalization to be `sept-2023` and accessing that same route in this PR will not show a flash of 404.
https://docs-getdbt-com-git-fix-404-flash-vercel-dbt-labs.vercel.app/docs/dbt-versions/release-notes/sept-2023/product-docs-summer

## Checklist

Removing or renaming existing pages (delete if not applicable):
- [ ] Remove page from `website/sidebars.js`
- [ ] Add an entry `website/static/_redirects`
- [ ] [Ran link testing](https://github.com/dbt-labs/docs.getdbt.com#running-the-cypress-tests-locally) to update the links that point to the deleted page

### CODE REVIEW

**Comment by matthewshaver** [comment]
Hi @john-rock - should we move forward with this PR? I can check for any other pages that may have capitalized letters.

**Comment by john-rock** [comment]
Hey @matthewshaver - I originally spun up this PR to determine if in fact it was the capitalization issue causing the 404 and it turns out indeed that was the case.

We have substask created in this [task](https://app.asana.com/0/1200099998847559/1205508339405074/f) to fix the casing throughout the site.

There are a few other instances of capitalized routes that will need to be updated and I'm happy to apply them all in this PR. If you have a list feel free to drop it in this PR. Once we have them all updated the PR should be good to merge. 

Does that work for you?

**Comment by matthewshaver** [comment]
@john-rock That works for me! I'll start reviewing to help y'all out. Thank you!

**Comment by nghi-ly** [comment]
@john-rock : i took a look at the task, thanks for the link! does it make sense to merge the proposed changes? or does it make sense to close this out and reopen if needed?

**Comment by john-rock** [comment]
Hey @nghi-ly feel free to merge this PR. 

As far as the rest of the routes that need the capitalization removed we can either:
1. Fix them on an as-needed basis.
2. Audit all file routes with capitals and fix them all in 1 PR.

I'll let your team make the call on that.

**Comment by runleonarun** [comment]
Being that @matthewshaver  is changing the way release notes work, I'm going to just close this. Let me know if you disagree and I'll re-open!

**Pull request closed without merging**
