### PR TITLE
Update building-models.md

### PR DESCRIPTION
**Pull request by amychen1776**
This sentence is repeating.

### CODE REVIEW

**Comment by clrcrl** [comment]
One could say it's repeated code...

**Comment by drewbanin** [comment]
i think this is funny and good FWIW

**Comment by clrcrl** [comment]
`:')`

**Comment by ghost** [comment]
i also think this is funny and good and funny and good

**Comment by amychen1776** [comment]
And this is why I will no longer be making PRs late into the night. 😭

**Pull request closed without merging**
