### PR TITLE
Update 2-staging.md

### PR DESCRIPTION
**Pull request by chekos**
## What are you changing in this pull request and why?

Noticed a typo while reading this guide

### CODE REVIEW

**Comment by runleonarun** [comment]
@joellabes This looks good to me! Should I merge?

**Comment by joellabes** [comment]
@chekos can you clarify why you think this is a typo?

Your suggested change would materialize models in the `staging` project under the `jaffle_shop` subdirectory as views, which isn't correct.

**Comment by mirnawong1** [comment]
it also seems to go against [this doc and example](https://docs.getdbt.com/reference/resource-configs/resource-path). this example is for the `project.yml` file, not your file tree -- did you think this was the file tree folder @chekos ?

**Comment by mirnawong1** [comment]
hey @chekos , checking on this. i'll go ahead and close this pr but if you have strong opinions, please feel free to re-open it or open a new one 🙏

**Pull request closed without merging**
