### PR TITLE
Update target_database.md

### PR DESCRIPTION
**Pull request by ialdg**
Hi.
This modification proposal is intended to correct a typo. Regards.
IL.

## Checklist

- [ ] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) so my content adheres to these guidelines.
- [ ] For [docs versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#about-versioning), review how to [version a whole page](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) and [version a block of content](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#versioning-blocks-of-content).
- [ ] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

Adding or removing pages (delete if not applicable):
- [ ] Add/remove page in `website/sidebars.js`
- [ ] Provide a unique filename for new pages
- [ ] Add an entry for deleted pages in `website/vercel.json`
- [ ] Run link testing locally with `npm run build` to update the links that point to deleted pages

### CODE REVIEW

**Review by mirnawong1 — APPROVED** [review]
🚢

**Comment by mirnawong1** [comment]
hey @ialdg , thanks for opening up this pr and we always appreciate your contributions, they help improve our docs for our users and community 🙏

I’m going to review some of your prs and noticed you have a knack for spotting areas that could benefit from more clarity or are confusing to readers :sparkles:  -- to make sure we tackle these the best way possible, I’m going to ask if you can channel that kind of feedback via opening a [docs issue](https://github.com/dbt-labs/docs.getdbt.com/issues). it’s the best way for us to sort through them, triage them, and address your wonderful feedback directly.

and if you find typos or have a specific change you want to add (like this PR), please absolutely keep those prs coming! they’ll help us keep the docs updated.

thank you again!

**Comment by ialdg** [comment]
Hi Mirna.
I'll just do that!
Sorry, but I didn't know I could follow that procedure. I used what I had
available 😳
Sorry for the inconveniences. I'll tray to avoid that sort of issues.
Regards.
IL.

**Comment by mirnawong1** [comment]
hey @ialdg , definitely no need to apologize at all! we absolutely appreciate your awesome contributions! we just realized it probably wasn't clear for users when they should open issues and when to open prs (which we're in the process of clarifying on our end!) and wanted to make sure you were aware since a lot of your prs has really fantastic suggestions! 

I'm looking forward to digging into your PRs today/next week and wanted to give you a heads-up 🙏 . thank you as always, and looking forward to your future contributions 💥

**Pull request merged**
