### PR TITLE
update admonition icons, navbar size, version 2.0 darkmode styles, fo…

### PR DESCRIPTION
**Pull request by zesuma**
…oter font size and padding updates

## Description & motivation

API documentation body content unreadable in dark mode
https://app.asana.com/0/1200099998847559/1203012540466286/f

API preview
https://deploy-preview-2046--docs-getdbt-com.netlify.app/dbt-cloud/api-v2

------------------------

Nesting and interactive states of folders
https://app.asana.com/0/1200099998847559/1203015036443298/f
within this Asana task there are a bunch of sub tasks that have been addressed and completed as well.

Preview:
https://deploy-preview-2046--docs-getdbt-com.netlify.app/

### CODE REVIEW

**Comment by mirnawong1** [comment]
thank you @zesuma, this is awesome! 

the main thing i noticed is that any links are hard to see, both in dark mode and light mode. i think making them a brighter color will fix this. 

Here are some screenshots to show you what i mean:

Screenshot 2022-09-22 at 10 22 07
Screenshot 2022-09-22 at 10 22 12
Screenshot 2022-09-22 at 10 24 18
Screenshot 2022-09-22 at 10 24 25

**Review by mirnawong1 — CHANGES_REQUESTED** [review]
requesting text with links to have a brighter color so it's easier to see in both dark and light mode. 

see above screenshots as examples. cc @jeremyyeo

**Comment by zesuma** [comment]
> 

let me know if this works for you?: https://deploy-preview-2046--docs-getdbt-com.netlify.app/dbt-cloud/api-v2

**Comment by mirnawong1** [comment]
looks so good, thank you for such quick work @zesuma ! lgtm and updated the branch for you to merge!

**Review by mirnawong1 — APPROVED** [review]

**Pull request merged**
