### PR TITLE
Developer blog draft

### PR DESCRIPTION
**Pull request by krevitt**
## Description & motivation
Docusaurus gives us a blog at /blog/ out of the box, which as part of @jasnonaz's Developer Hub proposal we'll want to start using soon.

This PR puts a down payment there by:

1) Removing the demo posts that ship w/ Docusaurus
2) Adding two new SQL tutorial posts
3) Adding a `Developer Blog` link to the `Learn` header nav bar

## To-do before merge
Open items before we ship the blog:

- [x] [Global author frontmatter](https://docusaurus.io/docs/blog#global-authors) not being recognized
- [x] Blog featured image not being picked up (would we expect it to be?)
- [x] [Blog sidebar](https://docusaurus.io/docs/blog#blog-sidebar) not appearing as should be default according to docs
- [x] `slug` in frontmatter not being recognized (URL path is being parsed from the filename as a fallback) - ideally we won't have `/yyyy/mm/dd/` in the URL path, as that can make redirects tedious to manage when posts are updated.

## Pre-release docs
Is this change related to an unreleased version of dbt?
- [ ] Yes: please
- [x] No: please ensure the base branch is `current`
- [ ] Unsure: we'll let you know!

## Checklist
If you added new pages (delete if not applicable):
- [ ] The page has been added to `website/sidebars.js`
- [x] The new page has a unique filename

[Link to preview](https://deploy-preview-808--docs-getdbt-com.netlify.app/blog)

### CODE REVIEW

**Comment by krevitt** [comment]
@JKarlavige last thing we overlooked in the build!  setting meta titles + descriptions for the blog index page (from the blog config settings), category pages (from categories.yml) and author pages (from authors.yml).  individual posts have title / meta applied correctly from the post.

**Comment by JKarlavige** [comment]
> @JKarlavige last thing we overlooked in the build! setting meta titles + descriptions for the blog index page (from the blog config settings), category pages (from categories.yml) and author pages (from authors.yml). individual posts have title / meta applied correctly from the post.

Good catch, pushed a commit to add those

**Comment by krevitt** [comment]
@JKarlavige added some styling updates (checklist below) from the #devhub crew.

one thing i'm curious about - on blog post pages, i think on wide screens we're letting the article container get wider than on a regular docs page, can you take a look?  ideally we match the docs look, with a narrower article container and the right sidebar left-aligned in the right gutter.

image

image

other items I modified in styling:
- [x] If no image is set for a post, do not display the blog image as the post featured image (leave the image out of the bloglistitem) - already display:none'd the featured image in styling, but let's avoid loading it
image
- [x] 1-wide post feed (as opposed to 2-wide) on blog index page
- [x] Add 'Developer Blog' as a right-aligned top-level nav item (rather than having it within Learn), so right-aligned nav would be (Developer Blog, Learn, Community)
- [x] display:none of blog featured image 
- [x] Added margin above right sidebar, reduced padding above left sidebar
- [x] Reduced font sizes throughout for readability

**Comment by JKarlavige** [comment]
@krevitt  Pushed an edit to reduce the size of the container for the blog. Also left-aligned the flex container which moves the right sidebar closer to the actual blog content. It's not 100% like how the docs are structured, but it's something that will let it be pretty close without having to restructure.

Let me know what you think, and if we want to adjust that part further I can reorganize how those sections are laid out to match the structure of docs.

**Review by lfracalossiFA — APPROVED** [review]
Great work, Jason. Looks like you really extended the functionalities of the Docusaurus blog. I think this will be a great boon to our Community folks and content creators.

**Review by jasnonaz — APPROVED** [review]
Ready to rock!

**Pull request merged**
