### PR TITLE
Update presto-profile.md

### PR DESCRIPTION
**Pull request by mirnawong1**
removed presto page from docs per slack thread here: https://dbt-labs.slack.com/archives/C02NCQ9483C/p1650874910411999

## Prerelease docs
If this change is related to functionality in a prerelease version of dbt (delete if not applicable):
- [ ] I've added versioning components, as described in ["Versioning Docs"](../contributing/versioningdocs.md)
- [ ] I've added a note to the prerelease version's [Migration Guide](../website/docs/docs/guides/migration-guide)

## Checklist
If you added new pages (delete if not applicable):
- [ ] The page has been added to `website/sidebars.js`
- [ ] The new page has a unique filename

If you removed existing pages (delete if not applicable):
- [x] The page has been removed from `website/sidebars.js`
- [x] An entry has been added to `_redirects`

### CODE REVIEW

**Comment by amychen1776** [comment]
Hey @mirnawong1! Thanks for doing this. I think you're going to want to update the table on the [Available Adapters page ](https://docs.getdbt.com/docs/available-adapters) as well.

**Comment by mirnawong1** [comment]
hey @amychen1776 ! many thanks and yes - i have a pr for that here as well: https://github.com/dbt-labs/docs.getdbt.com/pull/1372#issuecomment-1109493013

**Review by amychen1776 — APPROVED** [review]
Nice! Thanks!

**Review by runleonarun — APPROVED** [review]
🚢 it!

**Pull request merged**
