### PR TITLE
Update/slim ci does not require prod run

### PR DESCRIPTION
**Pull request by matt-winkler**
## What are you changing in this pull request and why?

`dbt compile` is a faster and cheaper way to snapshot the production manifest than doing a `dbt build`, so it should be our default recommendation for this workflow.

## Checklist
- [X] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) and [About versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) so my content adheres to these guidelines.
- [X] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."
- [ ] Needs technical review

### CODE REVIEW

**Comment by mirnawong1** [comment]
hey @matt-winkler, many thanks for opening up this pr! great content contribution and i'd like to loop in @schottj and @nghi-ly as it relates to the CI page.

**Comment by nghi-ly** [comment]
thanks @mirnawong1 !

hi @matt-winkler , there are plans to update these steps with new screenshots which will be published by the end of this month for phase 2 of the CI improvement project. 

because of this, i'm thinking we should hold off on updating them now. wdyt, @schottj ?

**Comment by matt-winkler** [comment]
That's awesome news @nghi-ly! In that case let's close this - thanks a ton.

**Comment by schottj** [comment]
@matt-winkler thanks for working on this!
@nghi-ly - I agree. Let's hold off as we're overhauling the set up steps anyways

**Comment by nghi-ly** [comment]
closing. thank you everyone! 🙌

**Pull request closed without merging**
