### PR TITLE
Remove create_metric parameter reference from 1.6 docs

### PR DESCRIPTION
**Pull request by tlento**
## What are you changing in this pull request and why?
The create_metric parameter on measures defined in semantic models is listed in the 1.6 documentation, but support for it was not added until 1.7.

This PR removes the create_metric entry from the 1.6 documentation.

## Checklist
- [x] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) and [About versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) so my content adheres to these guidelines.
- [x] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

### CODE REVIEW

**Comment by tlento** [comment]
The preview seems really broken to me, maybe I'm on the wrong branch? This needs to only go out to 1.6, as this parameter is supported in 1.7.

**Comment by mirnawong1** [comment]
hey @tlento ! thanks for opening this up, I've created a partial so we can reuse the same table because i noticed the parameters didn't match in the 'measures' page and 'semantic models' page. i also added an asterisk so all users were aware that `label` and `create_metric` is available on dbt v1.7 or higher.

**Comment by mirnawong1** [comment]
also @tlento this pr is going into the `1-6-ga` branch and not `current` branch -- is that right?

**Comment by mirnawong1** [comment]
hey @tlento , let me know if this is good to go and if the branch is going to the correct one -- should it be current?

**Comment by tlento** [comment]
Hi @mirnawong1 ! The original PR was targeted at 1-6-ga  because it was a fix for the create_metric documentation in the 1.6 version of the docs site.

With the new updates I think we should merge this to current. Will that back-propagate to the 1.6 version as well, or do we need to backport or something?

**Comment by tlento** [comment]
Also I think everything looks great from a language perspective but I can't render the docs in vercel for some reason so I don't know what it all looks like.

**Comment by mirnawong1** [comment]
hey @tlento ! no worries, sorry you can't view the vercel preview - what error or behavior are you seeing? 

I'll share the [staging link](https://docs-getdbt-com-git-tlento-create-metric-update-dbt-labs.vercel.app/docs/build/semantic-models#measures) and screenshots too in case it helps but it's looking good on my end! 

I'll merge this to the current branch but let me know if you think anything needs changing. thank you again!


Screenshot 2023-11-17 at 09 46 49
Screenshot 2023-11-17 at 09 47 08

**Review by mirnawong1 — APPROVED** [review]

**Pull request merged**
