### PR TITLE
Add private repo package settings to docs

### PR DESCRIPTION
**Pull request by tayloramurphy**
Went through this myself and thought it'd be good to add!

## Pre-release docs
Is this change related to an unreleased version of dbt?
- [ ] Yes: please
    - update the base branch to `next`
    - add Changelog components: `<Changelog>[New/Changed] in v0.x.0</Changelog>`
    - add links to the "New and changed documentation" section of the latest [Migration Guide](../website/docs/docs/guides/migration-guide)
- [x] No: please ensure the base branch is `current`
- [ ] Unsure: we'll let you know!

## Checklist
If you added new pages (delete if not applicable):
- [ ] The page has been added to `website/sidebars.js`
- [ ] The new page has a unique filename

If you removed existing pages (delete if not applicable):
- [ ] The page has been removed from `website/sidebars.js`
- [ ] An entry has been added to `_redirects`

### CODE REVIEW

**Comment by tayloramurphy** [comment]
@clrcrl for review please! 🙂

**Comment by clrcrl** [comment]
Is this true?! Gonna have to throw it to Drew to review ha

**Comment by tayloramurphy** [comment]
> Is this true?! Gonna have to throw it to Drew to review ha

Haha yeah! We're going to implement it here https://gitlab.com/gitlab-data/analytics/-/merge_requests/3564

**Comment by drewbanin** [comment]
Right on! You can also use the `ssh` url for the for a repo and make sure that users running `dbt deps` having their public key configured in the relevant git provider (with access to the relevant repo).

I think this is probably the _preferred_ approach, and I think it would be good to document each one! You buy it @tayloramurphy?

**Comment by tayloramurphy** [comment]
@drewbanin I do buy it. I'll test locally and update this PR in the coming week. I'll ping y'all when I have an update. Thanks!

**Comment by tayloramurphy** [comment]
@drewbanin I was able to get this working. The only catch is I believe dbt expects the configuration to always be in `~/.ssh/`. but otherwise it works great!

**Review by drewbanin — APPROVED** [review]
Thanks @tayloramurphy!! This looks great.

FYI you can also run something like:
```
$ GIT_SSH_COMMAND="ssh -i ~/path/to/ssh/dir/id_rsa" dbt deps
```

to use an SSH key in a different dir.... but that's a git thing and might not be worth documenting here at all.

**Comment by tayloramurphy** [comment]
@drewbanin I didn't realize that - that's useful on our end I think 🙂

**Pull request merged**
