### PR TITLE
WIP: Add markdown for docs homepage

### PR DESCRIPTION
**Pull request by clrcrl**
## Description & motivation
Update the home page

## To-do before merge
- [ ] Get this markdown rendering on the home page

### CODE REVIEW

**Comment by drewbanin** [comment]
@clrcrl what do you reckon about something like this?

Screen Shot 2020-04-13 at 6 59 36 PM

**Comment by clrcrl** [comment]
OK, you were right — I think this might be a little too plain (I miss the moving arrows)

But I don't want you to sink any more time into it. I think this gives me enough to write a good brief for Beth though!

**Comment by drewbanin** [comment]
Ok! We can actually keep the graph-viz-looking thing in there really easily. I removed it because it didn't look _great_ when it overlapped with the text.

I agree with your assessment though -- let's get Beth in here when we can -- I'm sure she'll do a much better job than I can :)

**Comment by clrcrl** [comment]
Closes #63

**Comment by clrcrl** [comment]
Closing in favor of #119

**Pull request closed without merging**
