### PR TITLE
Update Athena adapter references

### PR DESCRIPTION
**Pull request by nicor88**
## Description & motivation
[Tomme/dbt-athena](https://github.com/Tomme/dbt-athena) has been the main dbt-athena adatper around, 1 month ago the community decided to fork it, and push changes fastest in the new: https://github.com/dbt-athena/dbt-athena fork.
Various changes were added in the last week with faster peace thanks to the community. Now we support dbt 1.3.0 and Iceberg, and many more features were added recently.

This PR aims to update the main references, to point users to the right place when the want to use dbt in combination with Athena.

Worth to read [this](https://getdbt.slack.com/archives/C013MLFR7BQ/p1669476562984739) message in Slack

## Prerelease docs
If this change is related to functionality in a prerelease version of dbt (delete if not applicable):
- [x] I've added versioning components, as described in ["Versioning Docs"](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/versioningdocs.md)
- [x] I've added a note to the prerelease version's [Migration Guide](https://github.com/dbt-labs/docs.getdbt.com/tree/current/website/docs/guides/migration/versions)

## Checklist
If you added new pages (delete if not applicable):
- [x] The page has been added to `website/sidebars.js`
- [x] The new page has a unique filename

If you removed existing pages (delete if not applicable):
- [x] The page has been removed from `website/sidebars.js`
- [x] An entry has been added to `_redirects`
- [x] [Run link testing](https://github.com/dbt-labs/docs.getdbt.com#running-the-cypress-tests-locally) to update the links that point to the deleted page

### CODE REVIEW

**Comment by nicor88** [comment]
FYI @dataders

**Comment by nicor88** [comment]
@joellabes could you have a look at this one?

**Comment by runleonarun** [comment]
@amychen1776 @dataders Any feedback for this PR, or can I merge it?

**Review by dataders — APPROVED** [review]
beautiful -- thanks!

**Pull request merged**
