### PR TITLE
Update website/docs/reference/warehouse-setups/tidb-setup.md

### PR DESCRIPTION
**Pull request by Daemonxiao**
## Description & motivation
Add meta data: `min_core_version` and `min_supported_version`.

## Prerelease docs
If this change is related to functionality in a prerelease version of dbt (delete if not applicable):
- [ ] I've added versioning components, as described in ["Versioning Docs"](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/versioningdocs.md)
- [ ] I've added a note to the prerelease version's [Migration Guide](https://github.com/dbt-labs/docs.getdbt.com/tree/current/website/docs/guides/migration/versions)

## Checklist
If you added new pages (delete if not applicable):
- [x] The page has been added to `website/sidebars.js`
- [x] The new page has a unique filename

If you removed existing pages (delete if not applicable):
- [ ] The page has been removed from `website/sidebars.js`
- [ ] An entry has been added to `_redirects`
- [ ] [Run link testing](https://github.com/dbt-labs/docs.getdbt.com#running-the-cypress-tests-locally) to update the links that point to the deleted page

### CODE REVIEW

**Review by zhangyangyu — APPROVED** [review]

**Comment by Daemonxiao** [comment]
@runleonarun Please take a look.

**Comment by Daemonxiao** [comment]
@runleonarun Please take a look. 🙏

**Review by mirnawong1 — APPROVED** [review]
hey @Daemonxiao thanks for opening this up and approved this for you so you can merge. or let me know if you'd like me to merge it for you. thanks again!

**Comment by Daemonxiao** [comment]
@mirnawong1 Please merge this PR. Thank you.❤️

**Pull request merged**
