### PR TITLE
Adjust links to work with Docusaurus Link Component

### PR DESCRIPTION
**Pull request by JKarlavige**
## What are you changing in this pull request and why?

In PR #3000, we removed a custom `Link` component to utilize the built-in Docusaurus Link component. This uncovered a larger issue, where the old custom Link component was allowing links to be built in a way which Docusaurus does not support.

This PR fixes the broken links in the format which [Docusaurus recommends](https://docusaurus.io/docs/markdown-features/links), which allows us to use the built-in Link component. The built-in component offers additional features such as being able to download PDFs or other documents.

This PR is set to merge into PR #3000 when approved, where the update to the component is staged.

## Preview

https://deploy-preview-3065--docs-getdbt-com.netlify.app/

### CODE REVIEW

**Comment by lfracalossiFA** [comment]
Question: was the custom `Link` component linked (haha) to the incident we had six months or so ago?

**Comment by JKarlavige** [comment]
> Question: was the custom `Link` component linked (haha) to the incident we had six months or so ago?

Is that regarding the redirects issue? I can't say for sure, but i don't believe the custom component was specifically causing that. I believe that wasn't technically an issue, just the way React routing works where internal links don't make server requests, thus never firing the redirects.

But interested in seeing if that behaves differently here now that we're using the built-in component.

**Comment by lfracalossiFA** [comment]
> Is that regarding the redirects issue? 

Yep, that's the one!

> But interested in seeing if that behaves differently here now that we're using the built-in component.

Me too!

**Comment by matthewshaver** [comment]
https://www.notion.so/dbtlabs/Fixing-the-links-in-docs-72f9c4a8796f4724ba2b382c9e0ad8e6

**Comment by runleonarun** [comment]
The status is that Matt will begin work on fixing the relative links next week!

**Comment by JKarlavige** [comment]
Hey @matthewshaver, looking through this now!

**Comment by JKarlavige** [comment]
Updated this with `current` and  resolved the list of conflicts. With this up to date with `current`, there are some new broken links detected. I'll go through the new broken links (it's not nearly as painful as the original amount) and will push those updates.

**Comment by JKarlavige** [comment]
@matthewshaver All additional broken links are now sorted out and build is completing without any broken links detected. I marked you as a reviewer for this. Mind giving it one more look over, and if everything looks good want to give it the approval?

Feel free to loop anybody else in on the review, although i don't think it's realistic for anyone to check this many pages. 😅

**Review by matthewshaver — APPROVED** [review]

**Comment by matthewshaver** [comment]
@JKarlavige Looks good to me. Have reviewed with my team and we are ready to ship!

**Comment by JKarlavige** [comment]
@matthewshaver Sounds good! This will be merged into #3000 where the custom Link component is removed. I will merge this into 3000, will verify the build completes successfully, and will open that PR up for review before merging into `current`.

**Pull request merged**
