### PR TITLE
Update semantic-layer-6-advanced-metrics.md

### PR DESCRIPTION
**Pull request by Thelegendlink**
## What are you changing in this pull request and why?
Fix indent and incorrect filter and measure in `Ratio metrics` which are causing errors in implementing the code:
```sql
 - name: food_revenue
    description: The revenue from food in each order.
    label: Food Revenue
    type: simple
    type_params:
      measure: revenue
      filter: |
        {{ Dimension('order__is_food_order') }} = true
```
to
```
 - name: food_revenue
   description: The revenue from food in each order.
   label: Food Revenue
   type: simple
   type_params:
     measure: food_revenue
```

## Checklist

- [x] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) so my content adheres to these guidelines.
- [ ] For [docs versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#about-versioning), review how to [version a whole page](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) and [version a block of content](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#versioning-blocks-of-content).
- [x] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

### CODE REVIEW

**Comment by mirnawong1** [comment]
hey @Thelegendlink thanks for opening this pr! I'd like to loop in @Jstein77 to double check this as it looks like the indentation is part of the `type_params` for the food_revenue metric. because of this i think this is why it's currently the same indentation level as the other keys within type_params (e.g. like measure).

**Comment by Thelegendlink** [comment]
> `type_params`

Thanks for the prompt review @mirnawong1! Yeah that's causing an issue in parsing the config as `type_params` doesn't support a `filter` param, whereas `measure` does.

**Comment by Thelegendlink** [comment]
> > `type_params`
> 
> Thanks for the prompt review @mirnawong1! Yeah that's causing an issue in parsing the config as `type_params` doesn't support a `filter` param, whereas `measure` does.

Hmm there is another error after fixing the indent. 
1. `measure: food_revenue` instead of `measure: revenue`
1. It looks like the whole filter might need to be taken out as it relies on another model which is `orders`
```
    filter: |
      {{ Dimension('order__is_food_order') }} = true      
```
otherwise it's causing the error below:
```shell
Error #1:
  Message:

    The given input does not match any of the available group-by-items for
    Measure('food_revenue'). Common issues are:

      * Incorrect names.
      * No valid join paths exist from the measure to the group-by-item. 
        (fan-out join support is pending).
      * There are multiple matching join paths.
        (disambiguation support is pending).

    Suggestions:
      [
        "Dimension('order_item__is_food_item')",
        "Dimension('order_id__is_large_order')",
        "Dimension('order_item__is_drink_item')",
        "TimeDimension('order_id__ordered_at', 'day')",
        "TimeDimension('order_item__ordered_at', 'day')",
        "Entity('order_item__order_id')",
      ]

  Query Input:

    WhereFilter(
      ["{{ Dimension('order__is_food_order') }} = true",]
    )
    Filter Path:
      [Resolve Query(['food_revenue'])]
        -> [Resolve Metric('food_revenue')]
    Object Builder Input:
      Dimension('order__is_food_order')

  Issue Location:

    [Resolve Query(['food_revenue'])]
      -> [Resolve Metric('food_revenue')]
        -> [Resolve Measure('food_revenue')]
```

**Review by Jstein77 — APPROVED** [review]
Thanks for updating this @Thelegendlink!

**Comment by mirnawong1** [comment]
thanks again @Thelegendlink ! for the error you're encountering -- can you try the first suggestion: `Dimension('order_item__is_food_item')` ?

I'll get this merged for you though to make sure no one else runs into this issue!

**Comment by Thelegendlink** [comment]
> thanks again @Thelegendlink ! for the error you're encountering -- can you try the first suggestion: `Dimension('order_item__is_food_item')` ?
> 
> I'll get this merged for you though to make sure no one else runs into this issue!

Thanks @mirnawong1, it works with the following code:
```sql
    filter: |
       {{ Dimension('order_item__is_food_item') }} = 1
```

**Pull request merged**
