### PR TITLE
Update seed-configs.md

### PR DESCRIPTION
**Pull request by ialdg**
Hi.
This modification proposal is to correct a line of code. Since a configuration was made for:
seed file at `seeds/marketing/utm_parameters.csv`
, and that particular file name wasn't present, I added it. Regards.
IL.

## Checklist

- [x] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) so my content adheres to these guidelines.
- [ ] For [docs versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#about-versioning), review how to [version a whole page](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) and [version a block of content](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#versioning-blocks-of-content).
- [ ] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

Adding or removing pages (delete if not applicable):
- [ ] Add/remove page in `website/sidebars.js`
- [ ] Provide a unique filename for new pages
- [ ] Add an entry for deleted pages in `website/vercel.json`
- [ ] Run link testing locally with `npm run build` to update the links that point to deleted pages

### CODE REVIEW

**Review by nghi-ly — COMMENTED** [review]
thanks for opening this pr, @ialdg ! really appreciate your contribution! let me look into this for you.

**Comment by nghi-ly** [comment]
hiya @dbeatty10 : in reviewing this PR, i reread the [Seed config](https://docs.getdbt.com/reference/seed-configs) page. 

In the last paragraph in the section **Apply the schema configuration to one seed only**,  i see:

> In older versions of dbt, you must define configurations in dbt_project.yml and include the full resource path (including the project name, and subdirectories).

does this mean that _newer versions of dbt_ do not need the full resource path so [the current code example](https://docs.getdbt.com/reference/seed-configs#example-seed-configuration) in the section below is _correct_? thanks so much!

**Comment by dbeatty10** [comment]
Two things:

1. I think the point of the example in https://docs.getdbt.com/reference/seed-configs#example-seed-configuration is that all the seeds in the `seeds/marketing/` folder will have their schema overriden from `seed_data` to `marketing`.

    So I don't see anything wrong with the example, and I think we should close this PR without making any changes.

2. I'm guessing that the part where is says "In older versions of dbt, you must define configurations in `dbt_project.yml`" is pointing out that earlier versions didn't support configuring seeds in YAML like `seeds/marketing/properties.yml`. I didn't confirm this though.

**Comment by nghi-ly** [comment]
@dbeatty10 : thanks for taking a look at this and confirming. i thought the example looked correct but wanted to double-check.

**Comment by nghi-ly** [comment]
hello @ialdg : i checked with one of our engineers and it looks like the example is correct as is. closing but please do feel free to reopen if you want to discuss further.

**Pull request closed without merging**
