### PR TITLE
Update supported-data-platforms.md

### PR DESCRIPTION
**Pull request by mirnawong1**
fixing adapter link

## Prerelease docs
If this change is related to functionality in a prerelease version of dbt (delete if not applicable):
- [ ] I've added versioning components, as described in ["Versioning Docs"](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/versioningdocs.md)
- [ ] I've added a note to the prerelease version's [Migration Guide](https://github.com/dbt-labs/docs.getdbt.com/tree/current/website/docs/guides/migration/versions)

## Checklist
If you added new pages (delete if not applicable):
- [ ] The page has been added to `website/sidebars.js`
- [ ] The new page has a unique filename

If you removed existing pages (delete if not applicable):
- [ ] The page has been removed from `website/sidebars.js`
- [ ] An entry has been added to `_redirects`
- [ ] [Run link testing](https://github.com/dbt-labs/docs.getdbt.com#running-the-cypress-tests-locally) to update the links that point to the deleted page

### CODE REVIEW

**Review by dataders — APPROVED** [review]
:shipit: thanks @mirnawong1! TIL about the `category/` slug.


Relatedly, I just noticed that this markdown syntax URL isn't rendering properly. Anything fix you know of for this? cc: @JKarlavige 
image 
https://github.com/dbt-labs/docs.getdbt.com/blob/32faf39b5fae602dd97260d009c7bd79f7948916/website/sidebars.js#L68

**Comment by mirnawong1** [comment]
thanks @dataders , i'll stop short of merging this so Jason can respond 🙏

**Comment by JKarlavige** [comment]
Hey @dataders, I don't believe it's possible to add a link in the description field, it looks like it's expecting a plain string. I confirmed trying the html version of a link there does not work either.
image

**Comment by dataders** [comment]
> Hey @dataders, I don't believe it's possible to add a link in the description field, it looks like it's expecting a plain string. I confirmed trying the html version of a link there does not work either. image

ok! good to know! I'll tackle this in a future PR then

**Pull request merged**
