### PR TITLE
Feature/community spotlight

### PR DESCRIPTION
**Pull request by JKarlavige**
[Asana task](https://app.asana.com/0/1200099998847559/1202844016314455/f)

## Description & motivation

This adds a Community Spotlight section to the docs site, which includes the following:
- A spotlight index page
- Individual spotlight community member pages
- A section on the homepage, which pulls data from the existing spotlight member pages 

This also adds a `Spotlight` item to the navigation under `Community`.

Documentation is available here: https://www.notion.so/dbtlabs/Community-Spotlight-Member-f289869356bf423781d7bf9180a23dc3

## Preview

*Note - We are deploying without any active community spotlight members. There should be no changes visible on the site from this PR. The functionality will be (mostly) in place for when the DevHub team is ready to begin adding spotlight members.

https://deploy-preview-2423--docs-getdbt-com.netlify.app

## TODO before merge
- [x] Remove example spotlight member pages
- [x] Set `communitySpotlightMember` property in `docusaurus.config.js` to an empty string.

## Notes for when adding Community spotlight members in Q1
- The community spotlight navigation item is commented out within `docusaurus.config.js`.
- The buildSpotlightIndexPage plugin is commented out within `docusaurus.config.js`.
- The `getSpotlightMember` util function import and call is commented out in `website/src/pages/index.js`

### CODE REVIEW

**Review by john-rock — CHANGES_REQUESTED** [review]
I love the community spotlight idea and nice work on the implementation. I just have one requested changed and then two other questions.

1. Requested - Can we add a little bit of marging to the top of the cards on mobile? The Read More on the bottom of one card and the header image of the next card feel like they need some breathing room.
Community_spotlight___dbt_Developer_Hub

2. Question - Do we want the Community Spotlight block on the homepage appearing first on mobile before the Popular Resrouces blocks?

3. Question - This one isn't related to the task but I noticed the slider at the bottom of the homepage on mobile has the text extending outside of its container. If it isn't too much work would you be able to adjust that? If it's a bigger fix let's just open a task. This is on an iPhone 13 iOS 16.
dbt_Developer_Hub

**Comment by JKarlavige** [comment]
>     1. Requested - Can we add a little bit of marging to the top of the cards on mobile? The Read More on the bottom of one card and the header image of the next card feel like they need some breathing room.
>
>     2. Question - Do we want the Community Spotlight block on the homepage appearing first on mobile before the Popular Resrouces blocks?
> 
>     3. Question - This one isn't related to the task but I noticed the slider at the bottom of the homepage on mobile has the text extending outside of its container. If it isn't too much work would you be able to adjust that? If it's a bigger fix let's just open a task. This is on an iPhone 13 iOS 16.

1. For sure, i'll add some bottom margin for mobile.
2. That's a good question, i'll ask Emily in Asana!
3. Yeah i'll see if i can adjust that within this task, nice catch

**Review by breezyfasano — DISMISSED** [review]
LGTM, nothing additional to add!

**Review by john-rock — DISMISSED** [review]
Looks good after previous round of edits :shipit:

**Comment by JKarlavige** [comment]
@john-rock @breezyfasano Commented out a few items to prevent the spotlight index page from being built within this PR. We will be deploying these features as is with no spotlight members for now. TheDevHub team will be adding these in Q1.

Had to request another review due to the edits. No rush on getting to the review as there's no changes that will be visible on the site.

**Review by john-rock — APPROVED** [review]
lgtm!

**Pull request merged**
