### PR TITLE
Smart default documentation

### PR DESCRIPTION
**Pull request by Fleid**

### CODE REVIEW

**Comment by Fleid** [comment]
@matt-winkler FYI

**Comment by Fleid** [comment]
Postponing for now

**Comment by mirnawong1** [comment]
Hey @matt-winkler is this pr ok to close? Looks like it's been postponed?

**Comment by matt-winkler** [comment]
@mirnawong1 I'm fine either way.

**Comment by mirnawong1** [comment]
Closing this PR as this is postponed for now

**Pull request closed without merging**
