### PR TITLE
Clarify incremental model docs for unique_key configuration

### PR DESCRIPTION
**Pull request by compilerqueen**
## Description & motivation
Created for the coalesce hackathon in response to this issue: https://github.com/dbt-labs/docs.getdbt.com/issues/1888

These updates clarify the behavior of incremental models by consistently defining and referring to a "unique key configuraiton" and removing all references to a "uniqueness constraint". Additional helpful cross-section links and clarifications around multi-column keys are also added.

### CODE REVIEW

**Comment by compilerqueen** [comment]
This is now ready for review! I added as many cross-links as I could, and added some clarifications that have been helpful to my team internally. :) Please let me know if there's anything I can improve!

**Review by jasnonaz — DISMISSED** [review]
Absolutely fantastic addition to the docs - really helps clarify this THANK YOU 🙏

**Review by jasnonaz — APPROVED** [review]
We have appeased the netlify gods

**Comment by mirnawong1** [comment]
hey @jasnonaz is this pr good to merge?

**Comment by matthewshaver** [comment]
Merging as this was approved and awaiting Netlify errors that have been resolved

**Pull request merged**
