### PR TITLE
Arrow design for nav

### PR DESCRIPTION
**Pull request by JKarlavige**
## Description & motivation
[Asana task](https://app.asana.com/0/1200099998847559/1203075014761010/f)

This adjusts the rotation of the caret in the sidebar. Instead of:
- `v` for collapsed
- `^` for expanded

This changes it to:
- `>` for collapsed
- `v` for expanded 

## Preview
https://deploy-preview-2377--docs-getdbt-com.netlify.app/docs/introduction

### CODE REVIEW

**Review by john-rock — DISMISSED** [review]
I like it, lgtm!

**Comment by lfracalossiFA** [comment]
@JKarlavige This change is only for desktop sizes, correct? It looks like on mobile it's still up/down.

**Comment by JKarlavige** [comment]
> @JKarlavige This change is only for desktop sizes, correct? It looks like on mobile it's still up/down.

Goooooooood question, i'll ask Emily in the Asana task

**Comment by nghi-ly** [comment]
@JKarlavige : look and feel is fantastic! thank you! i wanted to also check the mobile version. is there a Netlify Deploy Preview for that?

**Review by nghi-ly — COMMENTED** [review]
@JKarlavige : look and feel is fantastic! thank you! i wanted to also check the mobile version. is there a Netlify Deploy Preview for that?

**Comment by JKarlavige** [comment]
> @JKarlavige : look and feel is fantastic! thank you! i wanted to also check the mobile version. is there a Netlify Deploy Preview for that?

Hey @nghi-ly, to view the mobile edits, you can either shrink your browser down until mobile styles kick in, or view the same preview link from your phone.

**Review by nghi-ly — APPROVED** [review]
🚢

**Pull request merged**
