### PR TITLE
Updated Continuous Integration Doc

### PR DESCRIPTION
**Pull request by schottj**
## Description & motivation

Updated the Using dbt Cloud: Enabling CI page to include some of the new functionality we're shipping with GitLab

## Pre-release docs
Is this change related to an unreleased version of dbt?
- [ ] Yes: please
    - update the base branch to `next`
    - add Changelog components: `<Changelog>[New/Changed] in v0.x.0</Changelog>`
    - add links to the "New and changed documentation" section of the latest [Migration Guide](../website/docs/docs/guides/migration-guide)
- [X] No: please ensure the base branch is `current`
- [ ] Unsure: we'll let you know!

If you removed existing pages (delete if not applicable):
- [ ] The page has been removed from `website/sidebars.js`
- [ ] An entry has been added to `_redirects`

### CODE REVIEW

**Comment by clrcrl** [comment]
Removing myself as reviewer :)

**Comment by drewbanin** [comment]
@schottj nice one! I was hoping to check this out in the Netlify staging env, but it looks like the deletion of the `package-lock.json` file is causing build errors? Any chance you could revert that deletion so the build passes?

**Comment by schottj** [comment]
@drewbanin 

I was confident the Netlify checks would pass, so I didn't wait around to confirm. Guess I learned not to do that! Should be good now:

https://deploy-preview-667--docs-getdbt-com.netlify.app/docs/dbt-cloud/using-dbt-cloud/cloud-enabling-continuous-integration-with-github

**Comment by drewbanin** [comment]
@schottj awesome! This looks really great. I think we'd just need to address the merge conflict on `website/package-lock.json` and then we'll be good to merge!

**Comment by schottj** [comment]
Think it's okay now. Just needed to do a git pull before I pushed. Once you approve, I'll wait to merge the code until we ship.

**Review by drewbanin — APPROVED** [review]
Alright! Approved! Let's merge when the change goes live :)

**Pull request merged**
