### PR TITLE
adding card component and ahref link note

### PR DESCRIPTION
**Pull request by mirnawong1**
updating component page to reflect new changes to card component, including the ability to add HTML ahref link inside the body and callout that link prop overrides ahref body links. [see loom](https://www.loom.com/share/c34967b5bd2945beb81061b43c4797be?t=80)

https://github.com/dbt-labs/docs.getdbt.com/pull/3120#event-8927247289

## Checklist

- [ ] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) and [About versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) so my content adheres to these guidelines.
- [ ] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

Adding new pages (delete if not applicable):
- [ ] Add page to `website/sidebars.js`
- [ ] Provide a unique filename for the new page

Removing or renaming existing pages (delete if not applicable):
- [ ] Remove page from `website/sidebars.js`
- [ ] Add an entry `_redirects`
- [ ] [Ran link testing](https://github.com/dbt-labs/docs.getdbt.com#running-the-cypress-tests-locally) to update the links that point to the deleted page

### CODE REVIEW

**Comment by nghi-ly** [comment]
@mirnawong1 : this PR looks like it's related to PR #3397 . double-checking with you, does it make sense to wrap up 3397 first? 

also curious why are there two places for this information. we may have chatted about this a while back and i forgot 😅

**Comment by mirnawong1** [comment]
> @mirnawong1 : this PR looks like it's related to PR #3397 . double-checking with you, does it make sense to wrap up 3397 first?
> 
> also curious why are there two places for this information. we may have chatted about this a while back and i forgot 😅

this pr was created back in April to reflect Breezy's awesome updates. i think i added it here because it's a page component that explains cards, whereas i thought the style guide is for our writing standards. do you think i should move this 'how to add card component' content to pr #3397 ? maybe this (page component page) is the correct location to go into detail about cards and how to configure them? 

this is def helpful as i also need to add an add'l functionality that allows us to carousel cards

**Comment by nghi-ly** [comment]
@mirnawong1 , totally agree with you that this should be documented somewhere since it's custom built. 

when i search the docs repo, the only place that links to the adding-page-components.md file is here in the repo's README https://github.com/dbt-labs/docs.getdbt.com/blob/current/README.md#writing-content. looks like it was originally created to document how to use Tabs -- today we're using what's built in to Docusauraus so we don't have to use the `<WHCode>` tag anymore to simulate tabs. 

personally, i like having the Markdown syntax/steps in the style guide itself where the guide describes what the rule/guideline is and also how to implement it. i wonder if this is a signal that maybe the section "Writing content" needs to be re-reviewed a bit, perhaps we've outgrown its original intent.

**Comment by mirnawong1** [comment]
> @mirnawong1 , totally agree with you that this should be documented somewhere since it's custom built.
> 
> when i search the docs repo, the only place that links to the adding-page-components.md file is here in the repo's README https://github.com/dbt-labs/docs.getdbt.com/blob/current/README.md#writing-content. looks like it was originally created to document how to use Tabs -- today we're using what's built in to Docusauraus so we don't have to use the `<WHCode>` tag anymore to simulate tabs.
> 
> personally, i like having the Markdown syntax/steps in the style guide itself where the guide describes what the rule/guideline is and also how to implement it. i wonder if this is a signal that maybe the section "Writing content" needs to be re-reviewed a bit, perhaps we've outgrown its original intent.

yea for sure! i didn't want to add it to the readme because i remember i was told we didn't want to pollute it for users, and likewise i was also told the style guide was getting long so I've been very aware of this feedback, which is why i added it to the tabs link under "writing content". i don't have bandwidth right now to rereview the writing content or style guide right but as a temp measure, what about moving over this content to the style guide but also include a blurb in the 'tabs' page so users can go to the style guide for more info?

**Comment by nghi-ly** [comment]
great callout, @mirnawong1 ! lemme try to take a stab at re-reviewing the "writing content" for us. if i can't get around to it be the end of the week, let's go with your temp measure. does that work for you?

**Comment by mirnawong1** [comment]
closing PR as there's a lot of convo on this thread and I'm not sure where we left off. pr opened since last apr and I've created a notion process to capture this card component change in a quicker way than a pr, particularly how to add HTML links inside the card.

**Pull request closed without merging**
