### PR TITLE
Added dbt-vertica Adaptor to Community Adaptors

### PR DESCRIPTION
**Pull request by arosychuk**
## Description & motivation
Added the dbt-vertica Adaptor to the list of Community Adaptors

## Pre-release docs
Is this change related to an unreleased version of dbt?
- [ ] Yes: please
    - update the base branch to `next`
    - add Changelog components: `<Changelog>[New/Changed] in v0.x.0</Changelog>`
    - add links to the "New and changed documentation" section of the latest [Migration Guide](../website/docs/docs/guides/migration-guide)
- [x] No: please ensure the base branch is `current`
- [ ] Unsure: we'll let you know!

## Checklist
If you added new pages (delete if not applicable):
- [x] The page has been added to `website/sidebars.js`
- [x] The new page has a unique filename

### CODE REVIEW

**Review by amychen1776 — APPROVED** [review]
Looks good to go! @ahedengren all I request is that the adapter repo gets updated to reference dbt labs rather than Fishtown Analytics due to our name change :)

**Comment by arosychuk** [comment]
Thanks for the PR @amychen1776! And yes, we have changed the name to dbt labs now. Nice catch.

**Comment by amychen1776** [comment]
@ahedengren I had to revert back the PR. Can you reopen it again but make sure to include the .md in the file name of the profile?

**Comment by arosychuk** [comment]
@amychen1776 my apologies. I've pushed another PR with that corrected.

**Comment by amychen1776** [comment]
No worries, the build failed so luckily didn't break our docs site :)

**Pull request merged**
