### PR TITLE
Update Spark adapter availability in dbt Cloud

### PR DESCRIPTION
**Pull request by boxysean**
## Description & motivation
Update the docs to reflect Spark's GA status in dbt Cloud.

## To-do before merge
- [ ] @saouderkirk can you make sure the information I'm presenting is accurate? I'm not sure if the other column should be "nearly full support", or both should be "nearly full support"

## Pre-release docs
Is this change related to an unreleased version of dbt?
- [ ] Yes: please
    - update the base branch to `next`
    - add Changelog components: `<Changelog>[New/Changed] in v0.x.0</Changelog>`
    - add links to the "New and changed documentation" section of the latest [Migration Guide](../website/docs/docs/guides/migration-guide)
- [x] No: please ensure the base branch is `current`
- [ ] Unsure: we'll let you know!

### CODE REVIEW

**Comment by drewbanin** [comment]
@boxysean thanks for opening this PR!! I think that we should:
- change "Databricks" to show ✅  instead of "preview"
- i think we can leave "nearly full support" as-is.... for now :)

**Comment by jtcohen6** [comment]
I hit this in https://github.com/fishtown-analytics/docs.getdbt.com/pull/638 as well. Agree with the suggested change, and with this update!

I was thinking recently that we should sub out `nearly full support` for ✅ . At some point, some adapters just won't support _every_ feature... but `dbt-spark` is by far the most mature community adapter today. Open to thinking more about the right words there.

**Comment by travis-fish** [comment]
(new to this, so correct me if I'm doing it wrong)
It feels like we might be ready to add Databricks as a native connector in the [Quickstart section](https://docs.getdbt.com/docs/dbt-cloud/cloud-quickstart#:~:text=dbt%20Cloud%20natively%20supports%20connections,can%20populate%20your%20warehouse's%20credentials).

**Comment by jtcohen6** [comment]
@boxysean I'm going to push a change to reconcile some of the proposed changes floating around, and the ongoing conversations about core/plugin and installation mechanisms

**Pull request merged**
