### PR TITLE
set table td to vertical-align: top;

### PR DESCRIPTION
**Pull request by zesuma**
## Description & motivation

Updated the table td's so that the text will now align to the top of the row with vertical-align: top;

https://app.asana.com/0/1200099998847559/1203158369764497/f

### CODE REVIEW

**Comment by mirnawong1** [comment]
hey @zesuma ! thanks so much for this and I've approved this for you.  I'm n to sure if it's just me but the deploy link still shows as the table looking uneven (right column)?? 
Screenshot 2022-10-25 at 11 50 21

**Review by mirnawong1 — APPROVED** [review]

**Comment by zesuma** [comment]
> hey @zesuma ! thanks so much for this and I've approved this for you. I'm n to sure if it's just me but the deploy link still shows as the table looking uneven (right column)?? Screenshot 2022-10-25 at 11 50 21

Hi @mirnawong1 I apologize I thought the ticket was asking to align the tables vertically not horizontally! The only issue with making each td equal width no matter the amount of content in each is you this will make the table look great when there are only 2 columns like so: 

image

 but if you have multiple columns with uneven content you get columns that look like this: 

image

You can see both tables here: https://deploy-preview-2297--docs-getdbt-com.netlify.app/docs/get-started/develop-in-the-cloud#start-up-and-work-retention-in-the-ide

Will this work for you or should we keep the td widths as they were?

**Comment by zesuma** [comment]
> 

heres the current live style on 3 columns: 
image

**Comment by mirnawong1** [comment]
hey @zesuma oh darn i see! ok yes you're right we should just keep the widths as they are because it makes the multiple columns with uneven content look super weird! should i close out this pr then?

thank you anyway for your wonderful help and i apologize for that!

**Comment by mirnawong1** [comment]
fyi @nghi-ly @matthewshaver @runleonarun so you're aware of the columns

**Pull request merged**
