### PR TITLE
Update idempotent.md: add word processing example

### PR DESCRIPTION
**Pull request by vergenzt**
Hi! I happened to just recently come up with the word processing example to explain idempotency to some colleagues, and then today noticed there's a dbt glossary page on the subject that was soliciting improvements. 🙂 

Let me know what you think!

### CODE REVIEW

**Comment by vergenzt** [comment]
Updated to fix casing on the failed "DML" term reference, remove the "This page needs some love" note, and revise the hover summary.

**Review by johnblust — APPROVED** [review]
This is awesome, @vergenzt Thank you so much for taking the time to work on this!! Your contribution here is definitely an improvement from what we had. Go ahead and hit that big green merge button whenever you're ready :)

**Comment by vergenzt** [comment]
If only I had permission (to click merge) I would! As it stands, however, I don’t have write access, so I can’t. 🙂

**Comment by vergenzt** [comment]
Thanks for the review! Happy to help. 👍

**Comment by johnblust** [comment]
Duh, sorry totally forgot about that. I'll get this merged. Thanks again!

**Pull request merged**
