### PR TITLE
Update set-dbt-semantic-layer.md

### PR DESCRIPTION
**Pull request by callum-mcdata**
## What are you changing in this pull request and why?
Updating for package version

### CODE REVIEW

**Review by mirnawong1 — DISMISSED** [review]
hey @callum-mcdata thanks for opening this up! approved for you to merge!

should this also be updated in the quickstart? i may make this into a snippet

**Comment by callum-mcdata** [comment]
@mirnawong1 if this information is also reflected in the quickstart then yes, we'd want it updated there as well.

**Comment by mirnawong1** [comment]
thanks @callum-mcdata ! i'm going to make that change in your branch if that's ok, so it's all consistent 🙏

**Review by mirnawong1 — APPROVED** [review]
approving this, thanks for the udpate @callum-mcdata ! [deploy preview](https://deploy-preview-2879--docs-getdbt-com.netlify.app/docs/use-dbt-semantic-layer/setup-dbt-semantic-layer) looks great!

**Pull request merged**
