### PR TITLE
Updates dbt icon for download

### PR DESCRIPTION
**Pull request by JKarlavige**
## Description & motivation
Update the dbt icon used within docs

## Pre-release docs
Is this change related to an unreleased version of dbt?
- [ ] Yes: please
    - update the base branch to `next`
    - add Changelog components: `<Changelog>[New/Changed] in v0.x.0</Changelog>`
    - add links to the "New and changed documentation" section of the latest [Migration Guide](../website/docs/docs/guides/migration-guide)
- [x] No: please ensure the base branch is `current`
- [ ] Unsure: we'll let you know!

https://deploy-preview-1130--docs-getdbt-com.netlify.app/docs/dbt-cloud/dbt-cloud-enterprise/setting-up-sso-with-okta

### CODE REVIEW

**Review by runleonarun — APPROVED** [review]
LGTM!!

**Comment by JKarlavige** [comment]
> LGTM!!

Thanks @runleonarun! Just pushed one more commit to update an image on that page which used the old logo as well. Just requested review!

**Comment by amy-byrum** [comment]
Screen Shot 2022-02-17 at 5 20 18 PM
Is this the link that was updated? 

Clicking it doesn't do anything for me, but it's possible that it's a netlify issue

**Review by runleonarun — APPROVED** [review]
This works for me!

**Comment by runleonarun** [comment]
@amy-byrum It may have been still building/netlify like you said.

**Comment by JKarlavige** [comment]
> Is this the link that was updated?
> 
> Clicking it doesn't do anything for me, but it's possible that it's a netlify issue

@amy-byrum I was seeing inconsistencies with this on my end as well. I moved the image over to getdbt.com, and am now linking to the image from there. This keeps similar functionality as when it was linking to google drive. I believe this should be corrected now, but let me know if you are still seeing any issues with it!

**Review by amy-byrum — APPROVED** [review]
lgtm! Thank you!

**Pull request merged**
