### PR TITLE
Update parse.md

### PR DESCRIPTION
**Pull request by will-sargent-dbtlabs**
## What are you changing in this pull request and why?
The dbt parse command supports the `--no-partial-parse` flag which is the only effective way to trigger a full reparse in the IDE, and get the results actually updated into the `perf_info.json` file.

## Checklist

- [ ] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) so my content adheres to these guidelines.
- [ ] For [docs versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#about-versioning), review how to [version a whole page](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) and [version a block of content](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#versioning-blocks-of-content).
- [ ] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

Adding or removing pages (delete if not applicable):
- [ ] Add/remove page in `website/sidebars.js`
- [ ] Provide a unique filename for new pages
- [ ] Add an entry for deleted pages in `website/vercel.json`
- [ ] Run link testing locally with `npm run build` to update the links that point to deleted pages

### CODE REVIEW

**Review by mirnawong1 — APPROVED** [review]
hey @will-sargent-dbtlabs thanks so much and looks great! i tweaked it a little - let me know if yo have any issues with it! happy to merge it on my end ✨!

also, this is for anything that's v1.5 and higher - is that ok?

**Comment by mirnawong1** [comment]
merging this for you!

**Comment by mirnawong1** [comment]
preview looks good! https://docs-getdbt-a373ufh26-dbt-labs.vercel.app/reference/commands/parse

**Comment by will-sargent-dbtlabs** [comment]
Thanks @mirnawong1 as always!  LGTM!  This was a "drive-by" docs update for me, so thanks for pushing it all the way through! :)

**Pull request merged**
