### PR TITLE
simplify unit testing example

### PR DESCRIPTION
**Pull request by graciegoheen**
## What are you changing in this pull request and why?

I updated the example for unit testing to simplify the code so it was easier to follow.

## Checklist

- [ ] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) so my content adheres to these guidelines.
- [ ] For [docs versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#about-versioning), review how to [version a whole page](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) and [version a block of content](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#versioning-blocks-of-content).
- [ ] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

Adding or removing pages (delete if not applicable):
- [ ] Add/remove page in `website/sidebars.js`
- [ ] Provide a unique filename for new pages
- [ ] Add an entry for deleted pages in `website/static/_redirects`
- [ ] Run link testing locally with `npm run build` to update the links that point to deleted pages

### CODE REVIEW

**Review by dbeatty10 — APPROVED** [review]
`simplified_example@awesome.com` 😎

**Comment by mirnawong1** [comment]
why am i this 🤏  close to adding bad gal riri in the 'badgmail.com' example 🫣🤣 (jks jks)

Screenshot 2024-02-22 at 09 41 52

**Comment by mirnawong1** [comment]
happy to get this merged for ya'll unless there are any objections!

**Comment by mirnawong1** [comment]
hey folks, merging this now! looking great: https://docs-getdbt-i06jaoaf8-dbt-labs.vercel.app/docs/build/unit-tests

**Pull request merged**
