### PR TITLE
An example of separating semantic model (pure yaml) from dbt model (yaml, sql, python)

### LINKED ISSUE #6306: An example of semantic model - parallel subfolder approach
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://github.com/dbt-labs/docs.getdbt.com/blob/current/website/docs/best-practices/how-we-build-our-metrics/semantic-layer-7-semantic-structure.md
Screenshot 2024-10-17 at 10 04 05 AM

### What part(s) of the page would you like to see updated?

I wasn't able to find an example of implementing the parallel subfolder approach unless I did it by trial and error or rigorously searched for other examples on Github, for example. https://github.com/dbt-labs/Semantic-Layer-Coalesce-2023/blob/main/models/metrics/fct_orders.yaml

### Additional information

I went ahead with a PR here but feel free to modify/adjust accordingly https://github.com/dbt-labs/docs.getdbt.com/pull/6305

### PR DESCRIPTION
**Pull request by albertlieyingadrian**
## What are you changing in this pull request and why?
It isn't a clear-cut to find an example of `sub-folder` [semantic approach](https://docs.getdbt.com/best-practices/how-we-build-our-metrics/semantic-layer-7-semantic-structure). Hence, adding an example of it. Additionally, adding it to [jaffle-shop repo](https://github.com/dbt-labs/jaffle-shop/tree/main/models/marts) would be wonderful.

Resolves #6306

## Checklist
- [x] I have reviewed the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) so my content adheres to these guidelines.
- [x] The topic I'm writing about is for specific dbt version(s) and I have versioned it according to the [version a whole page](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) and/or [version a block of content](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#versioning-blocks-of-content) guidelines.
- [x] I have added checklist item(s) to this list for anything anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

### CODE REVIEW

**Comment by albertlieyingadrian** [comment]
Or actually, adding a link to the tutorial of setting it up on Snowflake might be sufficient https://docs.getdbt.com/guides/sl-snowflake-qs?step=9
Screenshot 2024-10-17 at 12 48 11 PM

**Comment by albertlieyingadrian** [comment]
Lmk what else I need to change @runleonarun

**Review by mirnawong1 — APPROVED** [review]
hey @albertlieyingadrian , this is such a great pr! really beautifully written and thank you so much for opening this up to clarify! I'll probably follow up so i can link to your new header additions from the 'semantic structure' page and the quickstart, like you suggested.

i tweaked it a little and turn the h3 headers into expandable toggles, which are also linkable, just to shorten the scrolling needed and ensure the explanation is viewed too. 


I'm happy to merge this for you if you have no other comments/feedback. thank you again, this is such a great PR! ✨

**Comment by albertlieyingadrian** [comment]
No other comments. Please merge @mirnawong1

**Comment by jinjakim** [comment]
@albertlieyingadrian Woah this was you? - I was impressed on how the documentation had improved over the course of a week!

**Pull request merged**
