### PR TITLE
Cross database `type_{X}` macros

### LINKED ISSUE #1644: Add `type_{X}` macros to listing of cross-database macros
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

https://docs.getdbt.com/reference/dbt-jinja-functions/cross-database-macros

### What part(s) of the page would you like to see updated?

https://github.com/dbt-labs/dbt-core/pull/5428 and https://github.com/dbt-labs/dbt-utils/pull/586 move `type_{X}` macros from dbt-utils into dbt-core.

We want to create an entry for each containing:
- Arguments
- Usage
- Sample Output (PostgreSQL)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dbeatty10**
## Description & motivation
Resolves #1644 

## To-do before merge
- [x] Ensure https://github.com/dbt-labs/dbt-core/pull/5428 is merged
- [x] Ensure https://github.com/dbt-labs/dbt-utils/pull/586 is merged

## Prerelease docs
If this change is related to functionality in a prerelease version of dbt (delete if not applicable):
- [X] I've added versioning components, as described in ["Versioning Docs"](../contributing/versioningdocs.md)
- [X] I've added a note to the prerelease version's [Migration Guide](../website/docs/docs/guides/migration-guide)

### CODE REVIEW

**Review by jtcohen6 — APPROVED** [review]

**Review by dataders — COMMENTED** [review]
a few questions:

1) is it worth having a sidebar entry for each of the newly added macros, even if they just link to subheading on this page? It's a non-blocking issue, but my gut tells me the sidebar could be more helpful? Perhaps @gwenwindflower has some incremental guidance for us...
image

2) what is the intent behind the ["SQL Expressions" section](https://github.com/dbt-labs/docs.getdbt.com/blame/dbeatty/cross-database-type-X-macros/website/docs/reference/dbt-jinja-functions/cross-database-macros.md#L756-L786) at the bottom is it linked from elsewhere?

**Comment by dbeatty10** [comment]
> 1. is it worth having a sidebar entry for each of the newly added macros?

I'm not sure 🤷 Definitely interested in any feedback and ideas from you, @gwenwindflower, and others.

> 2. what is the intent behind the ["SQL Expressions" section](https://github.com/dbt-labs/docs.getdbt.com/blame/dbeatty/cross-database-type-X-macros/website/docs/reference/dbt-jinja-functions/cross-database-macros.md#L756-L786) at the bottom is it linked from elsewhere?

Yep, it is linked many, many times right now since expressions are a little tricky to explain and understand:

[Example](https://deploy-preview-1648--docs-getdbt-com.netlify.app/reference/dbt-jinja-functions/cross-database-macros#replace):

- image

Were you thinking it should live (or link) somewhere else?

**Comment by dataders** [comment]
> Were you thinking it should live (or link) somewhere else?

perhaps a standalone page? idc

**Comment by dbeatty10** [comment]
@dataders I merged this to get it out the door prior to the release candidate. But definitely feel free to re-organize by moving that section to a stand-alone page somewhere.

**Pull request merged**
