### PR TITLE
Update supported-data-platforms.md

### PR DESCRIPTION
**Pull request by alberttwong**
Adding StarRocks community adapter for DBT.

### CODE REVIEW

**Comment by mirnawong1** [comment]
hey @alberttwong , thanks for opening this pr up! wanted to double check if you're going to create another pr to the [warehouse-setups page](https://docs.getdbt.com/reference/profiles.yml)?  I'll also link you to our [adapter guide](https://docs.getdbt.com/guides/dbt-ecosystem/adapter-development/5-documenting-a-new-adapter), which provides more detail on how to do this.

**Comment by alberttwong** [comment]
I was hoping to just point it to the StarRocks page so that if issues get opened up, we would get notified.

**Comment by dataders** [comment]
@alberttwong to be included on our community adapter page, we ask that you write a "how to setup" page as described in [Documenting a new adapter](https://docs.getdbt.com/guides/dbt-ecosystem/adapter-development/5-documenting-a-new-adapter).

Let us know if you have any questions!

**Comment by matthewshaver** [comment]
Closing this as a duplicate. Using https://github.com/dbt-labs/docs.getdbt.com/pull/4290 to complete this task and add the StarRocks adapter to our pages

**Pull request closed without merging**
