### PR TITLE
Update/2.2.0

### PR DESCRIPTION
**Pull request by JKarlavige**
## Description & motivation

This updates Docusaurus to the latest version - 2.2.0. This includes reswizzling all existing components to get the latest updates, and reapplying any custom functionality. Since all the custom functionality had to be reapplied due to reswizzling, i've added a number of things to check for below.

## Preview Link

https://deploy-preview-2380--docs-getdbt-com.netlify.app/

### Announcement Bar / Nav
- [x] The entire announcement bar should be clickable, and not just a part of the text.
- [x] The version nav item should show `v<version-number>`
- - [x] Select a different version and verify the number in the navigation updates

### Blog Pages
- [x] On the [blog index page](https://deploy-preview-2380--docs-getdbt-com.netlify.app/blog), the 'dbt Developer Blog' banner should be available
- [x] Author names should be clickable and direct to their author page
- [x] Categories should be available in the blog sidebar
- [x] The breadcrumbs should update when clicking blog posts, categories, and authors
- [x] Individual category pages should show the category name and description at the top
- [x] Pagination should now be available on the blog index page
- [x] A CTA should be in the Table of Contents on the right. This is set in `website/blog/metadata.yml` and pulls from `website/blog/ctas.yml`

### Doc Pages
- [x] Visit a docs page such as https://deploy-preview-2380--docs-getdbt-com.netlify.app/reference/dbt-jinja-functions/set
- - [x] Change the version in the nav to `1.1`, a "NEW FEATURE" banner should appear
- - [x] Change to `v0.21`, a 2nd "Warning" banner should appear 
- - [x] The "Set" page linked above should be removed from the sidebar (Under Jinja Reference > dbt Jinja functions) for versions `1.1` or lower. This verifies the `versionedPages` within `website/dbt-versions.js` are working
- [x] The [Glossary](https://deploy-preview-2380--docs-getdbt-com.netlify.app/glossary) doc cards should show full description
- [x] The "Edit page" link on the right ToC should be available on every docs page, and clicking that should link to the correct page in Git.
- [x]  The `Expression Metrics` header on the [metrics page](https://deploy-preview-2380--docs-getdbt-com.netlify.app/docs/build/metrics) should only be available for version `1.2` or lower, and should be removed on `v1.3`.

### Styles Page
- [x] The 'view the intro' code block on the [styles page](https://deploy-preview-2380--docs-getdbt-com.netlify.app/styles) should be clickable.

## TODO Before Merge
- [x] Swizzle `DocItem` component
- [x] Swizzle `DocPage` component
- [x] Revert `featured_cta` to `staging` in `website/blog/metadata.yml`. This results in no current live CTA as `staging` cta not set
- [x] Get Admonitions working, example pages:
- - [x] [Blog post](https://deploy-preview-2380--docs-getdbt-com.netlify.app/blog/joining-snapshot-complexity)
- - [x] [Docs page](https://deploy-preview-2380--docs-getdbt-com.netlify.app/docs/build/incremental-models)
- [x] Clicking between the blog index & blog posts is wonky and inconsistent. Sometimes the banner on the blog index will persist on blog post pages, and sidebar occassionlly doesn't show up on the blog index. I believe it's tied to the custom edits i added in the BlogLayout component, specifically the `isBlogPost` & `isBlogList` checks.

## Notes
- I did not reswizzle the blog index page, as we no longer use the custom functionality (featured posts). I left all the default styling included with the new updates, I think they look better than what we have live now. Thoughts?

### CODE REVIEW

**Comment by john-rock** [comment]
Starting to take a look at this now.

**Review by john-rock — COMMENTED** [review]
Looks like the TOC CTA is not apply/missing the dark mode styles. Also looks like that CTA is opening in a new tab. Is that intentional?
image

**Review by john-rock — COMMENTED** [review]
This is only happening on the https://deploy-preview-2380--docs-getdbt-com.netlify.app/styles page. Incorrect text styles for the FAQ accordion on dark mode.

image

**Review by john-rock — COMMENTED** [review]
On all other pages with the FAQ accordions any item with a tooltip is difficult to read when on dark mode.
Snapshots___dbt_Developer_Hub

**Review by john-rock — COMMENTED** [review]
I'm also seeing quite a few broken links in this PR that are currently working on the live site.

https://deploy-preview-2380--docs-getdbt-com.netlify.app/docs/supported-data-platforms
- Both tables at the top all links are broken.

https://deploy-preview-2380--docs-getdbt-com.netlify.app/docs/build/exposures
- The two links under **Related documentation**

https://deploy-preview-2380--docs-getdbt-com.netlify.app/docs/build/metrics
- All the links under the **Benefits of defining metrics** header

**Review by john-rock — COMMENTED** [review]
This one is not a blocker and is currently happening on the live site. When trying to access a TOC item on mobile you need to double tap any of the items for the anchor link to work.
Supported_data_platforms___dbt_Developer_Hub

**Comment by john-rock** [comment]
> The breadcrumbs should update when clicking blog posts, categories, and authors

Are the breadcrumbs only suppose to be clickable on the blog pages? I just found myself trying to click them on the docs pages and only the Home breadcrumb is linked.

**Review by john-rock — COMMENTED** [review]
TOC are missing on mobile for blog posts.
image

**Review by john-rock — CHANGES_REQUESTED** [review]
Overall this looks really good for the amount of re-swizzling required for the update. Tested all of your checklist items and everything is good there. The two big things I saw were some style adjustments and then some broken links. The comment I left for the broken links are not a complete list just wanted to point out a few example. Lmk if I can clear up anything!

**Comment by JKarlavige** [comment]
@john-rock good finds, will start working through these

**Comment by JKarlavige** [comment]
> This one is not a blocker and is currently happening on the live site. When trying to access a TOC item on mobile you need to double tap any of the items for the anchor link to work.

For this, what browser/phone is this occurring in for you? Can't replicate it in chrome, firefox or on my samsung phone.

**Comment by JKarlavige** [comment]
> > The breadcrumbs should update when clicking blog posts, categories, and authors
> 
> Are the breadcrumbs only suppose to be clickable on the blog pages? I just found myself trying to click them on the docs pages and only the Home breadcrumb is linked.

The blog breadcrumbs are a custom feature we built. Only the `dbt Docs` & `Developer Blog` links in the blog breadcrumbs should be clickable, as the next item in the breadcrumbs should always be the page the visitor is currently on.

For the docs breadcrumbs, those are built-in with Docusaurus. All breadcrumbs should be clickable, but it looks like they're not. Using the Docusaurus site for reference, they should definitely be clickable: https://docusaurus.io/docs/markdown-features/tabs

Will look into the docs breadcrumbs to see why they're not clickable

**Comment by JKarlavige** [comment]
> > > The breadcrumbs should update when clicking blog posts, categories, and authors
> > 
> > 
> > Are the breadcrumbs only suppose to be clickable on the blog pages? I just found myself trying to click them on the docs pages and only the Home breadcrumb is linked.
> 
> The blog breadcrumbs are a custom feature we built. Only the `dbt Docs` & `Developer Blog` links in the blog breadcrumbs should be clickable, as the next item in the breadcrumbs should always be the page the visitor is currently on.
> 
> For the docs breadcrumbs, those are built-in with Docusaurus. All breadcrumbs should be clickable, but it looks like they're not. Using the Docusaurus site for reference, they should definitely be clickable: https://docusaurus.io/docs/markdown-features/tabs
> 
> Will look into the docs breadcrumbs to see why they're not clickable

Ah, okay i think i see what's going on, it looks like it's tied to the way we use the sidebar for a majority of the nested docs pages. For example on [this docs page](https://deploy-preview-2380--docs-getdbt-com.netlify.app/docs/get-started/getting-started/overview), the `Get started with dbt` breadcrumb is a "category" in our `sidebars.js` file and not a "doc". 

If you click that item in the sidebar, it only drops down more pages and does not actually link to a page. So it still shows in the breadcrumbs, but isn't actually a link, instead it's just showing the full path. [This page](https://docusaurus.io/docs/migration) within the Docusaurus site shows the same functionality.

The 2nd item within our glossary breadcrumbs on [this page](https://deploy-preview-2380--docs-getdbt-com.netlify.app/terms/data-catalog) for example works as "Analytics Engineering Glossary" is an actual page.

**Comment by john-rock** [comment]
> > This one is not a blocker and is currently happening on the live site. When trying to access a TOC item on mobile you need to double tap any of the items for the anchor link to work.
> 
> For this, what browser/phone is this occurring in for you? Can't replicate it in chrome, firefox or on my samsung phone.

Ah shoot forgot to specify. This is on an iPhone 13 iOS v16.0 with both Safari and Chrome apps.

**Comment by john-rock** [comment]
> > > > The breadcrumbs should update when clicking blog posts, categories, and authors
> > > 
> > > 
> > > Are the breadcrumbs only suppose to be clickable on the blog pages? I just found myself trying to click them on the docs pages and only the Home breadcrumb is linked.
> > 
> > 
> > The blog breadcrumbs are a custom feature we built. Only the `dbt Docs` & `Developer Blog` links in the blog breadcrumbs should be clickable, as the next item in the breadcrumbs should always be the page the visitor is currently on.
> > For the docs breadcrumbs, those are built-in with Docusaurus. All breadcrumbs should be clickable, but it looks like they're not. Using the Docusaurus site for reference, they should definitely be clickable: https://docusaurus.io/docs/markdown-features/tabs
> > Will look into the docs breadcrumbs to see why they're not clickable
> 
> Ah, okay i think i see what's going on, it looks like it's tied to the way we use the sidebar for a majority of the nested docs pages. For example on [this docs page](https://deploy-preview-2380--docs-getdbt-com.netlify.app/docs/get-started/getting-started/overview), the `Get started with dbt` breadcrumb is a "category" in our `sidebars.js` file and not a "doc".
> 
> If you click that item in the sidebar, it only drops down more pages and does not actually link to a page. So it still shows in the breadcrumbs, but isn't actually a link, instead it's just showing the full path. [This page](https://docusaurus.io/docs/migration) within the Docusaurus site shows the same functionality.
> 
> The 2nd item within our glossary breadcrumbs on [this page](https://deploy-preview-2380--docs-getdbt-com.netlify.app/terms/data-catalog) for example works as "Analytics Engineering Glossary" is an actual page.

Gotcha, that makes sense now!

**Comment by JKarlavige** [comment]
> > > This one is not a blocker and is currently happening on the live site. When trying to access a TOC item on mobile you need to double tap any of the items for the anchor link to work.
> > 
> > 
> > For this, what browser/phone is this occurring in for you? Can't replicate it in chrome, firefox or on my samsung phone.
> 
> Ah shoot forgot to specify. This is on an iPhone 13 iOS v16.0 with both Safari and Chrome apps.

I wonder if it's related to [this](https://tomanistor.com/blog/fixing-the-ios-mobile-double-click-link-issue/)

The mobile dropdown is being shown/hidden with display block/none. I'll try adjusting this to use opacity instead to see if that changes anything.

**Comment by JKarlavige** [comment]
Did more digging on the mobile TOC iOS issue of having to double-click. It looks like it's caused by the custom `useEffect` in our [DocItem component](https://github.com/dbt-labs/docs.getdbt.com/blob/f356bffb7cd8fac0c2486fb643a103acad5c7fb3/website/src/theme/DocItem/Layout/index.js#L43). Commenting out the useEffect, or passing in the original `toc` rather than `currentToc` into the `TOCCollapsible` component resolves the issue. There's a known iOS issue where pseudo css elements such as `:hover` cause issues for elements that aren't available on initial load. 

It looks like Docusaurus's way of handling this iOS/hover-state issue is by server-rendering the mobile TOC, which they have a comment in the stylesheet for: `/* Prevent hydration FOUC, as the mobile TOC needs to be server-rendered */`

We are updating the TOC on the client-side when the version is changed, and to add headers from Snippets. It looks like this occurs on the live site as well. I can think of three options:

1. Ideally we can resolve this issue with css, overriding the hover styles. But i haven't found a way and don't think it's worth investing that much more time into.
2. Pass in the original `toc` data, which wouldn't update on version changes and wouldn't have Snippet headers. But the toc links would work on first click on iOS.
3. Keep as is, having to double-click toc items when using an iphone.

Since it's already occurring on the live site, my vote would be for leaving it as-is, and noting this to try and resolve it during our Docusaurus improvements project. Ideally we would remove all this custom TOC work and use the built-in functionality like we talked about in our last standing meeting, and adjusting our components so they set the TOC items correctly in the first place, that's the root of our issue.

**Comment by JKarlavige** [comment]
All other fixes should now be in place:
- Blog TOC CTA fixed for dark mode
- FAQ styles fixed for dark mode
- Tooltips in FAQs fixed for dark mode
- Broken links should be fixed
- TOC added for blog posts

**Review by john-rock — DISMISSED** [review]
lgtm! Awesome work on this.

I agree we shouldn't let the TOC mobile issue block this.

**Comment by JKarlavige** [comment]
Hey @john-rock, I merged your search weight feature and had to make a slight adjustment for it to work with the new DocItem -> Layout component. Want to give it one more lookover when you have a moment? I tested locally and verified setting the `search_weight` frontmatter property correctly converts the `light/medium/heavy` string and adds the weight to the element. element on the page.

**Comment by JKarlavige** [comment]
@lfracalossiFA also adding you for a review on this.

**Comment by john-rock** [comment]
> Hey @john-rock, I merged your search weight feature and had to make a slight adjustment for it to work with the new DocItem -> Layout component. Want to give it one more lookover when you have a moment? I tested locally and verified setting the `search_weight` frontmatter property correctly converts the `light/medium/heavy` string and adds the weight to the element. element on the page.

Just took a look and tested. All lgtm!

**Comment by lfracalossiFA** [comment]
I'm going through the checklist now -- I expect I will have a few questions as I do!

One thing I'm curious about:
>  Categories should be available in the blog sidebar

When I open up [the blog](https://deploy-preview-2380--docs-getdbt-com.netlify.app/blog) on mobile, and open the hamburger button for the nav (which I assume we are using instead of the sidebar on mobile) instead of categories, I see a list of posts on that page. I have to click "back to main menu" in order to see categories. And for some reason when I do that, "sign up for a free account" is selected by default. See screenshots.

This is different than in production, so I wanted to make sure this behavior is intentional.

Screen Shot 2022-11-28 at 4 43 13 PM

Screen Shot 2022-11-28 at 4 44 00 PM

**Comment by JKarlavige** [comment]
> I'm going through the checklist now -- I expect I will have a few questions as I do!
> 
> One thing I'm curious about:
> 
> > Categories should be available in the blog sidebar
> 
> When I open up [the blog](https://deploy-preview-2380--docs-getdbt-com.netlify.app/blog) on mobile, and open the hamburger button for the nav (which I assume we are using instead of the sidebar on mobile) instead of categories, I see a list of posts on that page. I have to click "back to main menu" in order to see categories. And for some reason when I do that, "sign up for a free account" is selected by default. See screenshots.
> 
> This is different than in production, so I wanted to make sure this behavior is intentional.

It looks like this is default behavior for Docusaurus in the latest version, see: https://docusaurus.io/blog on mobile. The customization to show categories in the sidebar should only be on desktop. I'd prefer to roll with the default Docusaurus functionality as much as possible and avoid customizing the mobile menu to include categories, especially with it not being a specific request.

For the `Create a free account` nav item on mobile. That item has the teal background color in the desktop nav, and looks to carry over to mobile. It looks like the correct page has active styling, such as the blog in this case. But the different styling of the account button makes it look like it's selected as well. Think it's worth asking @emilymermell-dbt if we should change the styling for that button on mobile?

image

**Comment by lfracalossiFA** [comment]
I'm totally fine leaving the default Docusaurus behavior. It seems logical to my mind.

Let's ask @emilymermell-dbt are the link highlighting. But I don't think it's something that should block merging, either.

**Comment by JKarlavige** [comment]
> I'm totally fine leaving the default Docusaurus behavior. It seems logical to my mind.
> 
> Let's ask @emilymermell-dbt are the link highlighting. But I don't think it's something that should block merging, either.

Sounds good! Will ask emily in asana*

**Comment by lfracalossiFA** [comment]
Another question, @JKarlavige -- where should I be looking for this? Do you mean in the breadcrumb?

>  Individual category pages should show the category name and description at the top

**Comment by JKarlavige** [comment]
> Another question, @JKarlavige -- where should I be looking for this? Do you mean in the breadcrumb?
> 
> > Individual category pages should show the category name and description at the top

These are for the blog category pages, here's one for example! https://deploy-preview-2380--docs-getdbt-com.netlify.app/blog/tags/analytics-craft

And here's the full list of blog tags: https://deploy-preview-2380--docs-getdbt-com.netlify.app/blog/tags

**Comment by lfracalossiFA** [comment]
> A CTA should be in the Table of Contents on the right.

I assume this is only on desktop? (not sure where we'd even put it on mobile!)

**Review by lfracalossiFA — DISMISSED** [review]
Assuming we are okay with not having the TOC CTA on mobile, then I'm happy with these changes! 🚢

**Comment by JKarlavige** [comment]
> > A CTA should be in the Table of Contents on the right.
> 
> I assume this is only on desktop? (not sure where we'd even put it on mobile!)

Yep only on desktop! i believe that's how it is on the live site as well. I never _swizzled_ the `TOCCollapsable` component which is the mobile TOC component, so we never added the CTA to mobile CTAs.

**Comment by JKarlavige** [comment]
> Assuming we are okay with not having the TOC CTA on mobile, then I'm happy with these changes! 🚢

Woot thanks for looking it over! Going to notify the devhub team and will shoot to have this merged tomorrow morning!

**Comment by JKarlavige** [comment]
@lfracalossiFA @john-rock Just requested rereview. I saw it was approved, but I think the approval was removed after my latest commit.

**Review by lfracalossiFA — APPROVED** [review]

**Review by john-rock — APPROVED** [review]
lgtm!

**Pull request merged**
