### PR TITLE
Refactor: configs + properties

### LINKED ISSUE #616: Mention sources "external:" property in the documentation
## Steps to reproduce:
The [fishtown-analytics/dbt-external-tables/README.md](https://github.com/fishtown-analytics/dbt-external-tables/blob/master/README.md) says: 

> dbt v0.15.0 added support for an external property within sources that can include information about location, partitions, and other database-specific properties.

There is no mention of this property `external:` in the dbt documentation, I would expect a mention to it in one of this places:

* https://docs.getdbt.com/reference/source-configs
* https://docs.getdbt.com/reference/source-properties
* https://docs.getdbt.com/reference/dbt-jinja-functions/source

## Expected results:

I would expect to see at least 1 reference to the source's  `external` property in the documentation, at least mention it an point to https://github.com/fishtown-analytics/dbt-external-tables/blob/master/README.md,

### LINKED ISSUE #717: Add property file tags reference to page in docs
This page https://docs.getdbt.com/reference/resource-configs/tags should have a small note on the ability to label tags on individual models in properties.

image

See [this page](https://docs.getdbt.com/reference/resource-properties/tags), which probably needs a bit of beefing up itself.

### PR DESCRIPTION
**Pull request by jtcohen6**
> Two attributes, both alike in dignity,
> In fair dbt, which we make all green.
> From ancient split break to new unity
> Where simple code makes complex docs unclean

- Before: Configs and properties are two totally separate things, and confusingly so.
- After: There's a `config` property. Why can't they be friends?

By the by:
- resolves #616
- resolves #717

## Pre-release docs
Is this change related to an unreleased version of dbt?
- [x] Yes: please
    - update the base branch to `next`
    - add Changelog components: `<Changelog>[New/Changed] in v0.x.0</Changelog>`
    - add links to the "New and changed documentation" section of the latest [Migration Guide](../website/docs/docs/guides/migration-guide)
- [ ] No: please ensure the base branch is `current`
- [ ] Unsure: we'll let you know!

## Checklist
If you added new pages (delete if not applicable):
- [ ] The page has been added to `website/sidebars.js`
- [ ] The new page has a unique filename

If you removed existing pages (delete if not applicable):
- [ ] The page has been removed from `website/sidebars.js`
- [ ] An entry has been added to `_redirects`

### CODE REVIEW

**Comment by jtcohen6** [comment]
Reminder to self: also use this as an opportunity to document different merge behavior for configs. Namely, all configs are clobbered _except_:
- `tags`: additive
- `meta`: merged (clobbered by key)
- `pre-hook`, `post-hook`: additive

**Comment by jtcohen6** [comment]
I think this is ready for a first look from someone who isn't me. I'm going to continue iterating and self-reviewing. I'm hoping to have this live in `next` when we cut v0.21.0-rc1 end of week.

I ended up deleting less code than I expected, but I did do a lot of reorganization, and actually added new pages for properties that were previously sort of implied, such as `columns`.

**Comment by jtcohen6** [comment]
I'm going to merge this into `next` so that it's live at next.docs.getdbt.com in time for the `v0.21.0-rc1` announcement in discourse/slack. I'm going to turn around and open a PR from `next` into `current`, with specific requests for review ahead of the final release.

@jasnonaz If you get a chance, I'd still love a sense-check of the main point of entry: [**Configs, properties, what are they?**](https://deploy-preview-766--docs-getdbt-com.netlify.app/reference/configs-and-properties) We can talk more in the PR to come.

Screen Shot 2021-09-20 at 8 51 50 PM
Make a wish!

**Review by jasnonaz — COMMENTED** [review]
Excellent writeup!!! Great work JC.

**Pull request merged**
