### PR TITLE
rm staging cta, add setup tutorial cta

### PR DESCRIPTION
**Pull request by glin7**
## Description & motivation
Stop promoting Staging since the event has passed. Start promoting the new warehouse-specific tutorials instead.

### CODE REVIEW

**Comment by jasnonaz** [comment]
ahh great catch - thanks @glin7! I think @krevitt was thinking we'd switch this over to Coalesce promo curious to hear thoughts between the two

**Review by runleonarun — APPROVED** [review]
Great idea! I'm OK with this if everyone else is!

**Comment by glin7** [comment]
No strong opinion! Feel free to keep this PR on the back burner if we need to promote Coalesce instead. But if we're already pointing to Coalesce in other prominent positions on the site, might be nice to throw a little attention to other resources in smaller spots like this.

**Comment by krevitt** [comment]
Yep this works, we can mix in Coalesce soon but let's definitely swap this out

**Pull request merged**
