### PR TITLE
Update data test descriptions

### LINKED ISSUE #6293: [Core] Allow instances of generic data tests to be documented dbt-core #2578
At a minimum, update body to include a link to the page on docs.getdbt.com requiring updates and what part(s) of the page you would like to see updated.
 Originating from this issue: https://github.com/dbt-labs/dbt-core/issues/2578

Key changes include the addition of a `description` attribute to generic tests, updates to the parser to handle this new attribute, and new functional and unit tests to verify the implementation.

### Enhancements to Generic Data Tests:
* Added a `description` attribute to generic tests in `core/dbt/parser/generic_test_builders.py` to allow users to provide descriptions for tests, and ensured it is not passed into the test macro or name synthesis.
* Updated the `create_test_node` and `parse_generic_test` functions in `core/dbt/parser/schema_generic_tests.py` to include the `description` attribute in the test node metadata.

### PR DESCRIPTION
**Pull request by matthewshaver**
## What are you changing in this pull request and why?

Generic Test descriptions can now be documented

Closes https://github.com/dbt-labs/docs.getdbt.com/issues/6293

## Checklist
- [ ] I have reviewed the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) so my content adheres to these guidelines.
- [ ] The topic I'm writing about is for specific dbt version(s) and I have versioned it according to the [version a whole page](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) and/or [version a block of content](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#versioning-blocks-of-content) guidelines.
- [ ] I have added checklist item(s) to this list for anything anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

---
🚀 Deployment available! Here are the direct links to the updated files:

- https://docs-getdbt-com-git-test-description-dbt-labs.vercel.app/reference/resource-properties/description

### CODE REVIEW

**Comment by mirnawong1** [comment]
hey @matthewshaver , do you think we should modify one of the examples under the 'examples' header to include tests?

e.g. 

```
- name: color
  tests:
    - accepted_values:
        values: ['blue', 'green', 'red']
        description: "{{ doc('color_accepted_values') }}"

```

**Comment by mirnawong1** [comment]
also it maybe out of scope but would it be a good idea to link to the description property page [here](https://docs.getdbt.com/docs/build/documentation#adding-descriptions-to-your-project)?

**Comment by matthewshaver** [comment]
Good questions @mirnawong1 - I only updated to stress all data tests in the description. There was an earlier PR from some others that didn't do it then. Maybe because it would be a lot of version blocking

**Review by mirnawong1 — APPROVED** [review]
thank you @matthewshaver !

**Comment by joellabes** [comment]
My vote is to add some examples, even if they're not truly inside of version blocks and just have a comment beside them or something. I was just sharing info on how this worked, and wound up having to backsolve it myself instead of using the docs. 

A couple of examples are here if you want to leverage them: https://discourse.getdbt.com/t/is-it-possible-to-add-a-description-to-singular-tests/5472/4

**Pull request merged**
