### PR TITLE
homepage-first-draft

### LINKED ISSUE #63: Feature: docs home page
Random musings:
The docs.getdbt.com gives you a very clean landing page (but with little info), and if you click the "docs" link you get pushed straight into the Introduction.

I kind of like how in the [Django docs](https://docs.djangoproject.com/en/3.0/) there's a page which is like "here's where everything is". It makes it easier to get oriented quickly.

I'm not sure if this should live on the docs.getdbt.com landing page, or on docs.getdbt.com/docs

Anyway, just a thought 🤔

### PR DESCRIPTION
**Pull request by bethblinebury**
Closes #63

### CODE REVIEW

**Comment by clrcrl** [comment]
@bethblinebury — this looks _so_ great!

My general feedback is that I'd love to make the information just a tad more dense. I know that is probably counter to good design, but this page should lean slightly more towards utility. 

When I first opened this, I thought there was just the "getting started" section, and didn't realize there was more below it.

I'm imagining:
-  smaller boxes (250px height?)
- reduce the whitespace between each section (though I think they are responsive?)
- reduce the whitespace before "If you’re a dbt Cloud user, these resources may also be helpful:"

I played around with this on #121, but couldn't get the intra-section whitespace down. I also just made the headings consistently sized

**Comment by bethblinebury** [comment]
@clrcrl Great, let me make some tweaks! I am glad the initial draft is hitting the right chord. I'll report back.

**Comment by bethblinebury** [comment]
@clrcrl I merged #121 and made the additional adjustments you requested. I also added a subtle arrow-inspired visual to each card. Let me know what you think.

**Comment by clrcrl** [comment]
@bethblinebury — this looks so so so great!
> _The chevrons really add "texture", it doesn't seem so flat_
> - Drew

I'm absolutely happy to merge it as is, but we also had one other thought.

What do you think of adding icons for Discourse and Slack to the relevant cards, sort of as an indicator thank they link out somewhere?
https://fontawesome.com/icons/slack?style=brands
https://fontawesome.com/icons/discourse?style=brands

We are thinking to the left of the "Discourse" heading, but I'll take your design advice here!

**Comment by clrcrl** [comment]
Ah, I just noticed some weird scrolly behaviour where the card contents go above the header

**Comment by bethblinebury** [comment]
@clrcrl Whoops, let me adjust the z-index on the cards to prevent the overlap. 

I'm glad the chevron adds a nice, subtle visual element!

I like the idea of updating the discourse and slack cards. Let me make some updates! Stay tuned.

**Comment by clrcrl** [comment]
I am so glad you know what caused that issue — I've never heard "z-index" before in my life :joy:

**Comment by bethblinebury** [comment]
@clrcrl LOLZ it makes me sound fancy right?

**Comment by bethblinebury** [comment]
@clrcrl Does gbt/Fishtown Analytics already have a FontAwesome kit set up?

**Comment by clrcrl** [comment]
Erm not that I know of — I've used it in a past life. @drewbanin — do you know?

**Comment by bethblinebury** [comment]
@clrcrl @drewbanin Looks like there is a Font Awesome component for React that can be installed but that might be a bit beyond my React level experience. Thoughts?

**Comment by drewbanin** [comment]
hey @bethblinebury we use Entypo on most of our other websites. I just [made a branch](https://github.com/fishtown-analytics/docs.getdbt.com/compare/feature/add-entypo-fonts?expand=1) you can check out which adds the necessary entypo css to docusaurus - feel free to merge it, edit it, copy and paste, whatever, as needed :)

For reference, you can check out the icons in this glyph set here: https://www.getdbt.com/styles/

**Comment by clrcrl** [comment]
@drewbanin — I think Discourse is missing from that list. This is a little bit of a bigger ask than I realized, so I'm happy to ship this without icons. What do you think?

**Comment by drewbanin** [comment]
FYI Discourse [should actually be in there](https://github.com/fishtown-analytics/docs.getdbt.com/compare/feature/add-entypo-fonts?expand=1#diff-ef84f9d450a59a547b8ee5da646d84a1R350) -- it looks like the `/styles` site is out of date!

**Comment by bethblinebury** [comment]
@clrcrl I just pushed the updates with the Slack and Discourse icons. @drewbanin Thank you for updating the base to include the entypo.css. 

I think we're good to go.... Claire, I know you had mentioned me providing style suggestions for the rest of the docs. I can do a more thorough review but honestly nothing significant stood out. I think the new home page will add the right amount of visual interest and the internal pages are functioning in a very user-centric way in my opinion.

**Comment by clrcrl** [comment]
BETH THIS LOOKS SO GOOD!!!!

**Pull request merged**
