### PR TITLE
Fix examples for `dbt deps --add-package`

### PR DESCRIPTION
**Pull request by dbeatty10**
[Preview](https://docs-getdbt-com-git-dbeatty-fix-dbt-deps-add-package-dbt-labs.vercel.app/reference/commands/deps)

## What are you changing in this pull request and why?

Fixing the code examples per https://github.com/dbt-labs/dbt-core/issues/9076 by using test examples from https://github.com/dbt-labs/dbt-core/pull/8408

## Checklist
- [x] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) and [About versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) so my content adheres to these guidelines.
- [x] I've checked that the code examples work
- [x] I've confirmed that the preview renders correctly

### CODE REVIEW

**Comment by seub** [comment]
Thank you for creating this PR @dbeatty10.

While you're on this, the doc mentions:

> You can run `dbt deps --lock` to update the package-lock.yml with the most recent dependencies from packages

I could be wrong, but by glancing at the [code](https://github.com/dbt-labs/dbt-core/blob/017faf4bd18eefe030d87f61d6dd9e4a56cec020/core/dbt/task/deps.py#L212), it seems to me that this is inaccurate. The correct statement should be along the lines of:

> You can pass the flags:
> `--lock`: Create or replace the lock file if it does not exist or if `packages.yml` has changed, and stop (do not install the packages).
> `--upgrade`: Create or replace the lock file with the latest compatible versions, and install the packages unless the flag `--lock` is also passed.

Note: I actually like this "actual behavior" better than the behavior implied by the documentation. However, I don't see the need for both the flags `--dry-run` and `--lock`, they could be merged into a same flag as far as I can tell.

There is also a typo "depenedencies.yml" on the page.

**Review by matthewshaver — APPROVED** [review]
Thank you @dbeatty10

**Comment by dbeatty10** [comment]
@seub thanks for taking a look at this PR and making these suggestions 🏆

@mirnawong1 fixed the spelling of "dependencies" within 5e17f752cbf2f59c1ab32150dfe366a42b33152b.

I've opened this issue to consider your other suggestions: https://github.com/dbt-labs/docs.getdbt.com/issues/4481

**Comment by dbeatty10** [comment]
@seub also opened this feature request as well: https://github.com/dbt-labs/dbt-core/issues/9100

**Comment by seub** [comment]
Thank you @dbeatty10 ! 🙏

**Pull request merged**
