### PR TITLE
dbt-constraints-docs

### LINKED ISSUE #2594: dbt Constraints: Enforce data types, constraints, and checks on SQL table creation
### Contributions

- [X] I am a PM or subject matter expert at dbt who is responsible for this feature.

### Where does this content belong?

This belongs in a new page like this under the general configs section: https://docs.getdbt.com/reference/resource-configs/grants

### Link to source material

Pull Request: https://github.com/dbt-labs/dbt-core/pull/6271

### PR DESCRIPTION
**Pull request by sungchun12**
## To-do before merge

- [x] Ensure PR [#6271](https://github.com/dbt-labs/dbt-core/pull/6271) is merged
- [ ] Update migration guide specific to `1.5`
- [ ] Update version blocks for `1.5`

## Prerelease docs
If this change is related to functionality in a prerelease version of dbt (delete if not applicable):
- [x] I've added versioning components, as described in ["Versioning Docs"](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/versioningdocs.md)
- [ ] I've added a note to the prerelease version's [Migration Guide](https://github.com/dbt-labs/docs.getdbt.com/tree/current/website/docs/guides/migration/versions)

## Checklist
If you added new pages (delete if not applicable):
- [x] The page has been added to `website/sidebars.js`
- [x] The new page has a unique filename

### CODE REVIEW

**Comment by b-per** [comment]
As this relates to models only, would it make sense to move it under "for modes", either as a subitem or in "Model Configurations"?

We should also add the ability to set `constraints_enabled` to the "General configurations" part of the docs for models.

image

**Comment by sungchun12** [comment]
@b-per good call out. I'll make that change for section placement!

**Comment by sungchun12** [comment]
I was about to move the entire `constraints_enabled` page as a subsection under model configs, but then realized it gets cluttered and makes it hard to discover this information in the first place. I opted to create hyperlinks in the model configs page to the `constraints_enabled` page to make it easier to digest all the information in one place.

**Comment by sungchun12** [comment]
I'll wait to merge this closer to 1.5's release as many open issues may be complete and alter how contracts look and feel.

**Comment by jtcohen6** [comment]
@sungchun12 Thanks for the strong start here! Mind if I take over these docs from you? I want to take a swing at standing up the "wireframe" for model contracts — something we can share with devs and early beta testers alike — while also calling out the renaming & syntax changes that we have in the pipe.

**Comment by sungchun12** [comment]
@jtcohen6 go ahead and thanks for asking!

**Comment by jtcohen6** [comment]
I'm going to merge this into a new branch (`jerco/model-contracts`) so I can keep working on it there!

**Pull request merged**
