### PR TITLE
dbt-bigquery supports and enforces primary key constraints

### PR DESCRIPTION
**Pull request by dbeatty10**
### Previews
- [Terms: Primary key - Data warehouse support for primary keys](https://docs-getdbt-com-git-dbeatty-bigquery-primary-ke-d59f0b-dbt-labs.vercel.app/terms/primary-key#data-warehouse-support-for-primary-keys)
- [Model contracts: Platform constraint support](https://docs-getdbt-com-git-dbeatty-bigquery-primary-ke-d59f0b-dbt-labs.vercel.app/docs/collaborate/govern/model-contracts#platform-constraint-support)

## What are you changing in this pull request and why?

@bnaul called out [here](https://github.com/dbt-labs/dbt-bigquery/issues/865#issuecomment-1801995580) that some [documentation](https://docs.getdbt.com/terms/primary-key#google-bigquery) isn't in alignment with the [source code](https://github.com/dbt-labs/dbt-bigquery/blob/64e042a2349f17342f7af96d559e4e3a5138a49e/dbt/adapters/bigquery/impl.py#L115) (which asserts that dbt-bigquery supports and enforces primary key constraints).

Here are some other docs that should all be in alignment, but aren't:

### Model contracts: Platform constraint support

https://docs.getdbt.com/docs/collaborate/govern/model-contracts#platform-constraint-support

image

### constraints: Platform-specific support

https://docs.getdbt.com/reference/resource-properties/constraints#platform-specific-support

image

## Checklist
- [x] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) and [About versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) so my content adheres to these guidelines.
- [x] I've checked that the preview renders correctly
- [ ] I've checked that that code behaves as described

### CODE REVIEW

**Comment by bnaul** [comment]
Primary (and foreign) keys are supported but not enforced in BQ, so I think you only want the first change

**Comment by dbeatty10** [comment]
> Primary (and foreign) keys are supported but not enforced in BQ, so I think you only want the first change

Thank you!

Appreciate you pointing out that in BigQuery [Key Constraints are **not** enforced](https://cloud.google.com/blog/products/data-analytics/join-optimizations-with-bigquery-primary-and-foreign-keys) and are _only_ so the query optimizer may use this information to better optimize queries. As such, users will need to have [testing](https://docs.getdbt.com/docs/build/tests) in place to ensure primary key fields are unique and not null.

Our source code is currently asserting that they are [enforced](https://github.com/dbt-labs/dbt-bigquery/blob/64e042a2349f17342f7af96d559e4e3a5138a49e/dbt/adapters/bigquery/impl.py#L115-L116) (?!), so I've reached out to our engineering team for clarification. Guessing that we'll want to update the source code to be this instead:
```python
        ConstraintType.primary_key: ConstraintSupport.NOT_ENFORCED,
        ConstraintType.foreign_key: ConstraintSupport.NOT_ENFORCED,
```

Once that clarification comes in, will try to update all the different documentation pages and source code so that they are all in alignment.

**Comment by bnaul** [comment]
ah interesting, they most definitely [are not](https://cloud.google.com/bigquery/docs/information-schema-table-constraints) 😅 
image

**Review by mirnawong1 — APPROVED** [review]
lgtm and preview looks right!

**Pull request merged**
