### PR TITLE
Update exports.md

### PR DESCRIPTION
**Pull request by mirnawong1**
remove multi tenant as exports supports both mt and st.

### CODE REVIEW

**Review by DevonFulcher — APPROVED** [review]
Awesome thank you!

**Comment by mirnawong1** [comment]
amazing thank you so much @DevonFulcher !

**Comment by mirnawong1** [comment]
@DevonFulcher this might be a silly question - can i just confirm that exports also supports multi cell?

**Comment by DevonFulcher** [comment]
@mirnawong1 Good question! As far as I know, there is nothing preventing users from using Exports in MC

**Pull request merged**
