### PR TITLE
Change favicon color

### PR DESCRIPTION
**Pull request by lfracalossiFA**
## Description & motivation

Per this Asana task, we are changing the color of the favicon from orange to teal. https://app.asana.com/0/1200099998847559/1200627311270566/f

## Pre-release docs
Is this change related to an unreleased version of dbt?
- ✅  No

### CODE REVIEW

**Comment by drewbanin** [comment]
paging @amy-byrum - are we rolling with not-orange instances of the dbt logo? Wondering what our brand guidelines say on this front :)

Either way, do want to note that there's a white bg on the icon that renders poorly in dark mode! 

Screen Shot 2021-07-26 at 8 31 40 PM

**Comment by lfracalossiFA** [comment]
Ahh dark mode... always challenging us ;)

Thanks for bringing in Amy B... after requesting Madelyn's review I realized that Madelyn is out this week.

**Comment by amy-byrum** [comment]
Hello, hi! Thanks for the page. :) In the past, we had several different colors/versions of this logo floating around, but it's important we keep a grip on that in the future! We've reached a new level of brand maturity, and introducing one new variation could set a precedent that we don't actually want for our brand assets. Realistically there are two scenarios when we'd deviate from orange: 

- When we _need_ a monochrome version, say for print purposes
- For special events/occasions, such as Pride Month! 

I do understand the pain of dbt Cloud & docs using the same favicon, but I don't think the teal version is the answer. I'll get with Madelyn when she returns!

**Comment by lfracalossiFA** [comment]
Awesome, makes sense. Shall I close this PR out, then?

**Comment by lfracalossiFA** [comment]
Won't do

**Comment by drewbanin** [comment]
my favorite label in GitHub is #wontfix. I have a Spotify playlist called "Songs to #wontfix issues to" that i will _not_ be sharing at this time!

Thanks both :)

**Pull request closed without merging**
