### PR TITLE
Styling updates for 2021 dbt rebrand

### PR DESCRIPTION
**Pull request by JKarlavige**
## Pre-release docs
Is this change related to an unreleased version of dbt?
- [x] No: please ensure the base branch is `current`

### CODE REVIEW

**Comment by JKarlavige** [comment]
I noticed on mobile that the website does not fill the screen on the subpages. I believe this is a viewport issue. The Docusaurus viewport meta tag is set to `<meta name="viewport" content="width=device-width" />`, whereas the content attribute should also have an initial scale set to 1.

However, even after adding an updated viewport meta tag to the Head component, it looks like Docusaurus overrides that with it's own viewport tag. The only other option I see is to set an [ssrTemplate](https://docusaurus.io/docs/docusaurus.config.js/#ssrtemplate), but that looks like it will reconfigure the entire head based on what is added there.

**Comment by lfracalossiFA** [comment]
I see what you mean about the viewport! It happens in production, too:
https://docs.getdbt.com/docs/introduction

I assume you tried adding the meta tag to the /website/src/pages/index.js (for example, where the verification meta is?) That's the one that gets overridden?

(Have not reviewed yet; will review now)

**Comment by lfracalossiFA** [comment]
(Also you might also want to tag in @malbracht as a reviewer, since this is her design).

**Comment by lfracalossiFA** [comment]
<details><summary>Comment has been resolved by Lise Fracalossi</summary>

screenshot

Looks like button color still needs to change per comp.


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 92.0.4515.159 on Mac OS 10.15.7
Viewport:  1891 x 857 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-794--docs-getdbt-com.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=92.0&resolution=1891x857&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-794--docs-getdbt-com.netlify.app/) · [Mark as Unresolved](https://app.netlify.com/cdp/resolve?deployID=612cdf6422e0600008aae80b&commentID=612cfe48db24b06e8b07637b&resolution=unresolved)

</details>

**Comment by lfracalossiFA** [comment]
Actually, never mind, I goofed. It seems like she wants different tiers of buttons. I get it now. Ignore me!

**Comment by JKarlavige** [comment]
> I see what you mean about the viewport! It happens in production, too:
> https://docs.getdbt.com/docs/introduction
> 
> I assume you tried adding the meta tag to the /website/src/pages/index.js (for example, where the verification meta is?) That's the one that gets overridden?
> 
> (Have not reviewed yet; will review now)

Yes you are correct. For example I added in the link tags within that same Head component in the index file, and those are applied. However, if I add the viewport meta tag, it does not appear to update the existing one. I will add the updated meta tag to the latest commit to see if it overrides it on deployment.

**Review by lfracalossiFA — APPROVED** [review]
lgtm! :shipit: 

Jason, can you go ahead and make a new task in Asana to fix the viewport issue? I think you'll need to seek help from Drew on that... he may be the only one who understands how that works.

**Comment by JKarlavige** [comment]
> lgtm! :shipit:
> 
> Jason, can you go ahead and make a new task in Asana to fix the viewport issue? I think you'll need to seek help from Drew on that... he may be the only one who understands how that works.

Will do, creating the task now

**Pull request merged**
