### PR TITLE
Remove-1.6 from future releases table

### PR DESCRIPTION
**Pull request by dbeatty10**
Preview: [About dbt Core versions: Planned future releases](https://deploy-preview-4047--docs-getdbt-com.netlify.app/docs/dbt-versions/core#planned-future-releases)

## What are you changing in this pull request and why?

v1.6 is listed [here](https://docs.getdbt.com/docs/dbt-versions/core#planned-future-releases) as part of the "Planned future releases", so we should remove it now that it has been released.

## Checklist
- [x] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) and [About versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) so my content adheres to these guidelines.

### CODE REVIEW

**Comment by mirnawong1** [comment]
happy to get this merged but i'm wondering if we can just combine both tables. I'm going to try to mock something up and share here @dbeatty10

**Comment by mirnawong1** [comment]
hey @dbeatty10 , here's how i think it could look like. there's still some manual updates but at least it's updating once. 
one thing i was trying to do was see if i can add a dynamic badge that displays the release date but i can't seem to do it other than it being static. but it would be cool to have a badge that can automatically reflect the release date (and maybe even release status) [Microsoft does this similarly](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-release-schedule)

what do you think of the proposed table?

Screenshot 2023-09-08 at 13 01 21

**Comment by dbeatty10** [comment]
> there's still some manual updates but at least it's updating once.

Like your thinking about mitigating this issue happening again in the future 😎

## Options
Going the table route, we have 2 main options:
1. One unified table (like [Microsoft Edge](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-release-schedule#microsoft-edge-releases))
2. Separate tables for Supported, Unsupported, and Upcoming releases (like [Python](https://devguide.python.org/versions/#supported-versions))

Either way, I'm attracted to listing the releases from most recent to least. That way, the freshest (and most relevant) things are at the top and the oldest (least relevant) things are at the bottom.

## My opinion

From the perspective of a human trying to visually read the information, I'm also most attracted to three separate tables.

From the perspective of trying to ingest this data into a database table (or trying to keep thing in sync when updating 😉), then I'd prefer one unified table.

So my preference is something like this:

### Planned future releases

_Future release dates are tentative and subject to change._

| dbt Core                                                   | Initial Release | Support Level | Critical Support Until  | 
|------------------------------------------------------------|-----------------|----------------|-------------------------|
|  **v1.9**                                               | _Apr 2024_ |       | _Apr 2025_            | 
|  **v1.8**                                               | _Jan 2024_ |       | _Jan 2025_            | 
|  **v1.7**                                               | _Oct 2023_ |       | _Oct 2024_            | 

### Supported Versions

| dbt Core                                                   | Initial Release | Support Level | Critical Support Until  | 
|------------------------------------------------------------|-----------------|----------------|-------------------------|
| [**v1.6**](/guides/migration/versions/upgrading-to-v1.6)   | Jul 31, 2023    | Active         | Jul 30, 2024            |
| [**v1.5**](/guides/migration/versions/upgrading-to-v1.5)   | Apr 27, 2023    | Critical       | Apr 27, 2024            | 
| [**v1.4**](/guides/migration/versions/upgrading-to-v1.4)   | Jan 25, 2023    | Critical       | Jan 25, 2024            | 
| [**v1.3**](/guides/migration/versions/upgrading-to-v1.3)   | Oct 12, 2022    | Critical       | Oct 12, 2023            | 

### Unsupported Versions

| dbt Core                                                   | Initial Release | Support Level | Critical Support Until  | 
|------------------------------------------------------------|-----------------|----------------|-------------------------|
| [**v1.2**](/guides/migration/versions/upgrading-to-v1.2)   | Jul 26, 2022    | End of Life* | Jul 26, 2023            |
| [**v1.1**](/guides/migration/versions/upgrading-to-v1.1) | Apr 28, 2022    | End of Life* | Apr 28, 2023            | 
| [**v1.0**](/guides/migration/versions/upgrading-to-v1.0) | Dec 3, 2021     | End of Life* | Dec 3, 2022           | 
|  **v0.X**                                               | (Various dates) | Deprecated  | Deprecated            | 

_*All versions of dbt Core since v1.0 are available in dbt Cloud until further notice. Versions that are EOL do not receive any fixes. For the best support, we recommend upgrading to a version released within the past 12 months._

## Summary

I don't have strong feeling on the table placement, row ordering, or table format of the "planned future releases". But my eye and brain does prefer it to be visually separated from the "supported" and "unsupported" releases.

The emojis were a little intense for me (and they shouldn't be necessary with separate tables), so I dropped them above so we can see how it looks and feels.

**Comment by mirnawong1** [comment]
hey @dbeatty10 i've learned from you 🙏 

i did see python's table and i love it too! but the reason i sugg the unified table approach is because in the future, we'd have to update all 3 tables when a version changes. another reason is - what makes an 'unsupported version' unsupported? 1.0-1.2 are still available in dbt cloud and i think it's confusing to say they're 'unsupported' when they're still available in cloud. [see slack thread](https://dbt-labs.slack.com/archives/C0131TY7EEA/p1683054263740429) for context on orgs upgrading. 

i wish that this could be done/shifted automatically! I think you're right about the order, best to be descending. i'll go ahead and merge this pr for you to not hold it up but i'll open up an issue as it's worth a good discussion.

**Review by mirnawong1 — APPROVED** [review]

**Pull request merged**
