### PR TITLE
navbar titles now have a hover and fixed the padding issue

### PR DESCRIPTION
**Pull request by zesuma**
## Description & motivation

preview: https://deploy-preview-2175--docs-getdbt-com.netlify.app/

I've combined 3 tickets into this one:

**Nesting and interactive states of folders**
https://app.asana.com/0/1200099998847559/1203010186078425/f

**Font size is different in IDE GA launch user documentation**
https://app.asana.com/0/1200099998847559/1203134802011321/f

**Fonts in toggle snippet are different sizes**
https://app.asana.com/0/1200099998847559/1203118391233000/f

**Changes made:**

1. Sidebar nesting has been fixed. When you hover over the main title of the dropdown menu, the background color is activated.
2. The indentation has standardized indentation. 
3. Font sizes inside toggle snipets and tables is now 18px

### CODE REVIEW

**Comment by JKarlavige** [comment]
Adding a preview link here with a table to view the updated table font sizes: https://deploy-preview-2175--docs-getdbt-com.netlify.app/docs/supported-data-platforms

**Comment by JKarlavige** [comment]
And a preview link with a toggle: https://deploy-preview-2175--docs-getdbt-com.netlify.app/docs/building-a-dbt-project/snapshots

**Review by JKarlavige — APPROVED** [review]
All is looking good to me! Let's have the stakeholders weigh in for the individual tasks as well to make sure all looks as expected

**Comment by callum-mcdata** [comment]
This LGTM - I can't confirm whether the behavior I noticed is still present because it was found in another PR. But its low stakes so good enough for me!

**Comment by thorn14** [comment]
Looks like the interactive states are resolved and nesting is uniform. However, some of the initial issues with how the nesting is perceived exist, going to submit a separate PR to alleviate that issue to allow these other changes through.

see -> https://github.com/dbt-labs/docs.getdbt.com/pull/2180

**Review by thorn14 — APPROVED** [review]

**Pull request merged**
