### PR TITLE
Hacky rebuild of toc inside DocsItem

### PR DESCRIPTION
**Pull request by breezyfasano**
## Description & motivation
Please see this Asana task for description of the bug this PR is addressing:
https://app.asana.com/0/1200099998847559/1202893358534505/f

This essentially rebuilds the TOC on any docs page and adds any additional headers to the TOC if they are present on the page, not already in the Docusaurus created TOC (i.e. are from a `Snippet` component in the body of a document), and are h2s or h3s.

[Preview Link Here](https://deploy-preview-2373--docs-getdbt-com.netlify.app/docs/get-started/getting-started/building-your-first-project/build-your-first-models#another-test-very-important)

## Known Issues
- [x] If 2 headers are of the same level and has the same text content, Docusaurus generates a duplicate ID. Therefore, all TOCs will link to the first instance.
- Example: [FAQs on this page](https://deploy-preview-2373--docs-getdbt-com.netlify.app/docs/get-started/getting-started/building-your-first-project/build-your-first-models#build-models-on-top-of-other-models)
- [FIX: Setting an explicit ID as detailed here.](https://docusaurus.io/docs/next/markdown-features/toc#heading-ids)

## To-do before merge
- [ ] Remove dummy data in `tutorial-build-models-atop-other-models.md`

### CODE REVIEW

**Comment by JKarlavige** [comment]
This looks good to me! Headers within snippets look to be added to the TOC correctly, and clicking the link in the TOC brings the page to the correct section. Also wrapped the Snippet within a VersionBlock and verified TOC headers are removed if not available for the specified version. TOC is also working on mobile.

You made a lot of good finds on the root cause here yesterday. Definitely would like to get that worked into the quarterly improvements project to have headers from custom components be added to the TOC automatically.

Just a heads up there's a few console logs to nuke in the DocItem, along with those test headers. But this looks ready to merge after that, nice work!! :shipit:

**Review by JKarlavige — DISMISSED** [review]
:shipit:

**Comment by breezyfasano** [comment]
Thanks so much @JKarlavige :-) I'm going to let Ly review visually and then I'll ship it!

**Review by nghi-ly — DISMISSED** [review]
looks great! thank you!

**Review by JKarlavige — APPROVED** [review]
lgtm! :shipit:

**Pull request merged**
