### PR TITLE
Add Pat's Stakeholder-friendly Model Names blog

### LINKED ISSUE #1270: Why Focus on Model Naming Conventions?
### Contact Details

@patkearns10

### This issue is being created to promote an approved Discussion.

- [ ] I am promoting this issue from an approved Discussion and will link it below.

### Link to the Discussion this Issue is promoting.

This article predates the Discussion system, and has been outlined and drafted already. It's starting directly as an issue.

### If you're promoting this from an 'I want to write about...' Discussion, you can copy over the answers to the following questions. Otherwise, please answer these questions below

This article predates the Discussion system, and has been outlined and drafted already. It's starting directly as an issue. https://github.com/dbt-labs/dbt-technical-blog-writing/issues/68#event-5806117853

### Link to the initial outline we will develop through this Issue.

https://docs.google.com/document/d/1u4KUEdj_Ff0k6Llsal8eguPoQ2rQpE5Q2tQeRw8HGm0/edit?usp=sharing

### PR DESCRIPTION
**Pull request by johnblust**
Adds content and images

## Checklist
If you added new pages (delete if not applicable):
- [ ] The page has been added to `website/sidebars.js`
- [x] The new page has a unique filename

If you removed existing pages (delete if not applicable):
- [ ] The page has been removed from `website/sidebars.js`
- [ ] An entry has been added to `_redirects`

### CODE REVIEW

**Review by KiraFuruichi — COMMENTED** [review]
Yeah I think this looks great! Only two things I want to call-out:
- Are there any areas we could add some internal links to this? Particularly around the DAG/project stuff?
- Is this section here supposed to be in code or are the ticks like this on purpose?
image

**Comment by johnblust** [comment]
> Are there any areas we could add some internal links to this? Particularly around the DAG/project stuff?

I'll look into this, but nothing comes to mind

> Is this section here supposed to be in code or are the ticks like this on purpose?

@KiraFuruichi Yeah, they were originally code snippets, but it looked weird bolded as mini headers. So, I used \ to have the CMS ignore the formatting. Do you think I should remove the ticks?

**Comment by KiraFuruichi** [comment]
> @KiraFuruichi Yeah, they were originally code snippets, but it looked weird bolded as mini headers. So, I used \ to have the CMS ignore the formatting. Do you think I should remove the ticks?

Hmm I'd maybe ask Pat what he prefers (he should be online now). I think the ticks would look a little funky for people who aren't familiar with markdown!

**Comment by KiraFuruichi** [comment]
Also to note for future content: Following Leona's accessibility doc, it would be great if we could write out any abbreviations (once!) like we do for the rest of the docs site! There's a lot of AE/DAG/BI/PR used throughout this blog piece, which I think is totally cool because this post has some baseline assumptions about its audience (people with dbt experience), but if we're promoting this in a LI/twitter post, there could people who come to this page without any prior dbt experience.

**Comment by johnblust** [comment]
@KiraFuruichi So true, totally forgot the ticks were primarily a markdown thing. I just put them back to their original state.

Also, great call on the abbreviations. I made those changes!

Let me know if there's else needed here to get this approved.

**Review by KiraFuruichi — APPROVED** [review]
magnifique!

**Pull request merged**
