### PR TITLE
Fix duplicate title tags development

### PR DESCRIPTION
**Pull request by zesuma**
## Checklist

- [ ] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) and [About versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) so my content adheres to these guidelines.
- [ ] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

Adding new pages (delete if not applicable):
- [ ] Add page to `website/sidebars.js`
- [ ] Provide a unique filename for the new page

Removing or renaming existing pages (delete if not applicable):
- [ ] Remove page from `website/sidebars.js`
- [ ] Add an entry `_redirects`
- [ ] [Ran link testing](https://github.com/dbt-labs/docs.getdbt.com#running-the-cypress-tests-locally) to update the links that point to the deleted page

### CODE REVIEW

**Review by JKarlavige — DISMISSED** [review]
lgtm!

**Review by JKarlavige — APPROVED** [review]
lgtm!

**Comment by mirnawong1** [comment]
hey @zesuma @JKarlavige (apologies Jason for pinging during your offsite 🙏 ) - but it looks like this pr has changed the sidebar labels to the frontmatter title - is that what this is suppose to do? makes the sidebar look weird? 
Screenshot 2023-05-02 at 15 54 46

**Comment by mirnawong1** [comment]
i'm seeing this here too - apologies i don't have context on why this change was needed - IMHO it looks a bit weird especially since other files/pages don't have this structure

Screenshot 2023-05-02 at 16 00 41

**Comment by runleonarun** [comment]
@JKarlavige and @zesuma can the Docs team revert this PR and add better titles?

**Comment by JKarlavige** [comment]
@runleonarun For sure, definitely feel free to revert this. Additional work may be needed, either updating the titles, or using the `sidebar_label` frontmatter property for creating better titles for the sidebar.

I will leave a note for Emily in the Asana task that this will be reverted and will loop you and @mirnawong1 in there.

**Comment by runleonarun** [comment]
Thank you all! This PR has been reverted and the new [PR is here](https://github.com/dbt-labs/docs.getdbt.com/pull/3325).

**Pull request merged**
