### PR TITLE
Update ci-jobs.md

### PR DESCRIPTION
**Pull request by Tonayya**
## What are you changing in this pull request and why?

Added a suggestion on a recently reported issue with CI job run status update as per [this Zendesk ticket](https://dbtcloud.zendesk.com/agent/tickets/60166). Please let me know if you'd like the contents of the correspondence in the ticket to be shared. This has been tried, tested and confirmed internally. Please also advise on the text formatting, if any changes need to be made. Thanks team! 

## Checklist
- [x] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) so my content adheres to these guidelines.

### CODE REVIEW

**Comment by mirnawong1** [comment]
hey @Tonayya , thanks for opening this up and happy to review this! 

cc @nghi-ly I'm wondering if we should turn all the 'details' block toggles into the `detailsToggle` component? let me know if you're ok with that and I'll make that change in this pr. 

Screenshot 2024-02-08 at 14 53 05

**Comment by mirnawong1** [comment]
review complete and made some tweaks, thank you so much @Tonayya ! Screenshot 2024-02-08 at 14 53 56

**Comment by nghi-ly** [comment]
@mirnawong1 : yes, please! love the detailsToggle idea!

**Review by mirnawong1 — APPROVED** [review]
lgtm, thanks so much @Tonayya !

**Pull request merged**
