### PR TITLE
Move v1.2 adapter upgrade guide to separate page

### PR DESCRIPTION
**Pull request by jtcohen6**
## Description & motivation

@dataders added a ton of great content to the migration guide relevant for adapter maintainers in #1691. However, this content is ONLY relevant to maintainers of adapter plugins (a few dozen people), and the primary audience for the upgrade/migration guide is all dbt users (thousands).

This PR moves this content into its own dedicated page, so that it takes up less real estate in the general-purpose migration guide. **Question:** Is a docs.getdbt.com page the right place for this content? Would it be better as a GitHub discussion (easier to edit/update, see questions from other maintainers)?

In a separate commit, I also removed the section about `get_csv_sql()`. While there's nothing inherently wrong with the addition of this macro in dbt-labs/dbt-core#5207, this did NOT accomplish the thing we hoped it would in `dbt-snowflake`, for some very tricky reasons: https://github.com/dbt-labs/dbt-adapters/issues/740

### CODE REVIEW

**Review by dataders — CHANGES_REQUESTED** [review]
@jtcohen6 my idea here is to move the adapter migration guide to a GitHub discussion rather than a separate section of migration guides... perhaps we close this instead?

**Comment by jtcohen6** [comment]
closing!

**Comment by dataders** [comment]
> @jtcohen6 my idea here is to move the adapter migration guide to a GitHub discussion rather than a separate section of migration guides... perhaps we close this instead?

here is where the adapter guide will live. note to self to link out to this in the end-user upgrade guide, perhaps as well in the doc's contributing section?
https://github.com/dbt-labs/dbt-core/discussions/5468

**Comment by jtcohen6** [comment]
> note to self to link out to this in the end-user upgrade guide

✅

**Pull request closed without merging**
