### PR TITLE
Implement ESLint

### PR DESCRIPTION
**Pull request by JKarlavige**
## What are you changing in this pull request and why?

[Asana task](https://app.asana.com/0/1200099998847559/1203760149887729/f)

This introduces ESLint to automate formatting for markdown and JS files. 

There are two areas where ESLint runs:
- Locally when making a commit, this checks only changed files
- In a Git Action which runs on every push to a PR. This checks all files.

## Testing

To test, open a file and add improperly formatted code. In this example, I added an undefined variable to `website/src/components/author/index.js`.
image

Notice the variable now shows an error within VSCode.

Now i'll try to make a commit. The commit fails due to the `error`: `'breakstuff is not defined`. This has prevented me from making a commit due to the error. The warnings show here due to the error, however ESLint is currently configured to allow `warnings` through in commits.
image

## Notes

There is a separate PR (#2969) where the existing ESLint issues are fixed. I will merge that PR into here when approved.

Here is prior ESLint Git Action run where `errors` were found: https://github.com/dbt-labs/docs.getdbt.com/actions/runs/4376123948/jobs/7657782506

## Checklist
- [x] Setup ESLint with Husky
- [x] Setup an ESLint check within PRs

### CODE REVIEW

**Comment by john-rock** [comment]
Hey @JKarlavige are there any settings that need to be changed within the IDE itself?

I have this in my local, removed node_modules, ran `npm i`, but still not seeing any errors for an undefined var I set. Tried to commit that file as well and was able to commit without any errors thrown.

**Comment by JKarlavige** [comment]
> Hey @JKarlavige are there any settings that need to be changed within the IDE itself?
> 
> I have this in my local, removed node_modules, ran `npm i`, but still not seeing any errors for an undefined var I set. Tried to commit that file as well and was able to commit without any errors thrown.

Ahhh, shoot. Yes there is. `npm run prepare` which configures Husky. Good catch. Going to look into seeing if there's a way to automate that part

**Comment by john-rock** [comment]
> > Hey @JKarlavige are there any settings that need to be changed within the IDE itself?
> > I have this in my local, removed node_modules, ran `npm i`, but still not seeing any errors for an undefined var I set. Tried to commit that file as well and was able to commit without any errors thrown.
> 
> Ahhh, shoot. Yes there is. `npm run prepare` which configures Husky. Good catch. Going to look into seeing if there's a way to automate that part

Right on, just ran `npm run prepare` and confirming errors are now being thrown!

image

**Comment by JKarlavige** [comment]
> > Hey @JKarlavige are there any settings that need to be changed within the IDE itself?
> > I have this in my local, removed node_modules, ran `npm i`, but still not seeing any errors for an undefined var I set. Tried to commit that file as well and was able to commit without any errors thrown.
> 
> Ahhh, shoot. Yes there is. `npm run prepare` which configures Husky. Good catch. Going to look into seeing if there's a way to automate that part

Added a `prestart` script which runs automatically when starting the site locally. If Husky isn't installed, it will install it at that time right before the site starts up. Let me know what you think or if there's any concerns with that.

**Review by john-rock — DISMISSED** [review]
This lgtm. I don't see any concern with automating the husky install on `npm start`

Confirming that prestart command works.
image

Confirming the errors are now being thrown for an undefined var within the code as well as in the terminal on commit preventing the commit from taking place.
image

**Comment by JKarlavige** [comment]
Hey @runleonarun! Wanted to loop you in on this, this is part of the docs improvements project for this quarter. This PR adds ESLint for code checking, which includes a git workflow to check the code before merging. [Here](https://github.com/dbt-labs/docs.getdbt.com/actions/workflows/lint.yml) is the workflow runs from this PR, and you can view how they work when they find errors.

This also will check the code locally and will prevent us from committing any code when ESLint finds issues. Curious what you think, and if we should keep this workflow in the PRs.

https://github.com/dbt-labs/docs.getdbt.com/actions/workflows/lint.yml

**Comment by runleonarun** [comment]
@JKarlavige I think this would be good to merge and test out. The only test failure that prevents you form merging a PR is the netlify deploy one so it's low risk of workflow disruption on our end!

**Comment by JKarlavige** [comment]
ESLint checks passed, @john-rock it looks like it marked your review as stale. May you give it the approval one more time if all looks good? This is clear to merge after that!

**Comment by john-rock** [comment]
Looking at this now!

**Review by john-rock — APPROVED** [review]
lgtm! Good work :shipit: 

- Confirmed `npm run prepare` is triggered when running `npm start`
- Confirmed errors are called out within the code while developing
- Confirmed commits are blocked when those errors are not addressed.

**Pull request merged**
