### PR TITLE
detailsToggle fast follow

### PR DESCRIPTION
**Pull request by mirnawong1**
this pr updates the code i the following sections because the ux was a little weird if you immediately clicked on the toggle after it expanded:

- `handleToggleClick` flips the current open/close state (!current), and ensures hover is always active.
- `handleMouseEnter`checks if the content is already open (isOn) before enabling hover 
- `handleMouseLeave` enables so that the content closes only if it's not already open due to a click.

### CODE REVIEW

**Review by JKarlavige — APPROVED** [review]
This looks good to me! Able to hover over the items to show the details as well as clicking them. Clicking them fast does not seem to cause any odd behavior! :shipit:

**Comment by mirnawong1** [comment]
awesome! thank you sooo much @JKarlavige !

**Comment by JKarlavige** [comment]
> awesome! thank you sooo much @JKarlavige !

For sure, nice work on the fix!!

**Comment by mirnawong1** [comment]
adding [this slack convo](https://dbt-labs.slack.com/archives/C02NCQ9483C/p1702914423862069?thread_ts=1702672761.975359&cid=C02NCQ9483C) for more context and explaination

**Pull request merged**
