### PR TITLE
Updating order of examples

### LINKED ISSUE #4417: Standardize the order of code examples for `dbt_project.yml` vs. `properties.yml`
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### Link to the page on docs.getdbt.com requiring updates

- https://docs.getdbt.com/reference/resource-configs/group
- https://docs.getdbt.com/reference/resource-configs/enabled
- https://docs.getdbt.com/reference/resource-configs/meta

### What part(s) of the page would you like to see updated?

Here's an example where `dbt_project.yml` is first and `models/_.yml` is second:

image

My initial instinct is that this should be the order to standardize upon, but we could choose the other way around if we want to.

Let's pick an order and stick with it.

[Here's](https://docs.getdbt.com/reference/resource-configs/group) an example where the order is opposite:

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by matthewshaver**
## What are you changing in this pull request and why?

Standardizes the `project.yml` file as the first example on a few pages where it's listed after the `models` example.

Closes https://github.com/dbt-labs/docs.getdbt.com/issues/4417

## Checklist

- [x] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) and [About versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) so my content adheres to these guidelines.
- [x] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

### CODE REVIEW

**Review by runleonarun — APPROVED** [review]
Much easier to read! Only one comment for [Analyses here](https://docs-getdbt-com-git-project-order-dbt-labs.vercel.app/reference/resource-configs/group) is there no dbt_project example?

**Comment by matthewshaver** [comment]
> Much easier to read! Only one comment for [Analyses here](https://docs-getdbt-com-git-project-order-dbt-labs.vercel.app/reference/resource-configs/group) is there no dbt_project example?

I'll ask in a follow up - this doesn't have one in prod today so I'm not sure if it's missing or not required

**Comment by dbeatty10** [comment]
> > Much easier to read! Only one comment for [Analyses here](https://docs-getdbt-com-git-project-order-dbt-labs.vercel.app/reference/resource-configs/group) is there no dbt_project example?
> 
> I'll ask in a follow up - this doesn't have one in prod today so I'm not sure if it's missing or not required

Good eyes @runleonarun!

The reason is that analyses [can't be](https://github.com/dbt-labs/docs.getdbt.com/pull/3989#pullrequestreview-1604506567) configured within `dbt_project.yml`:

> There's a distinction between attributes we call "configs" and attributes we call "properties," in that "configs" can be set for many resources at once in `dbt_project.yml`, and "properties" can only be set for one resource at a time. The fact is that macros and analyses _only_ have properties, and that's why they cannot be configured from `dbt_project.yml`.

**Comment by runleonarun** [comment]
@dbeatty10 always such a great teacher! Thanks for the explanation

**Pull request merged**
