### PR TITLE
Create help feed embeds for a handful of pages

### PR DESCRIPTION
**Pull request by joellabes**
## Description & motivation
A follow on made possible by #2004 - we can embed help Q&As with specific tags into the bottom of pages.

### CODE REVIEW

**Comment by joellabes** [comment]
Example: https://deploy-preview-2195--docs-getdbt-com.netlify.app/docs/build/seeds 

but the tags weren't being applied properly; I fixed it (I think) but then Netlify stopped doing builds 😢 hoping this will fix itself overnight

**Review by jasnonaz — APPROVED** [review]
This is so cool!

**Review by runleonarun — APPROVED** [review]
Approving but we should do something to make these pages less busy post Coalesce. Perhaps remove FAQs?

**Review by jasnonaz — CHANGES_REQUESTED** [review]
@joellabes I caught up with Leona who rightfully raised the point that this could be overwhelming all at once - can we pilot a smaller set of pages to include this on for the initial rollout then we can add more as we get design + user feedback

**Comment by john-rock** [comment]
Hey folks just pushed a commit on this to limit the number of returned Discource topics to 3 for the `DiscourseHelpFeed` component per the request in this [task](https://app.asana.com/0/1200099998847559/1203158602320482/f). [Example here](https://deploy-preview-2195--docs-getdbt-com.netlify.app/docs/build/incremental-models).

**Comment by joellabes** [comment]
> pilot a smaller set of pages to include this on for the initial rollout

@jasnonaz @runleonarun I've removed the ones that already had FAQs - if there are others you want to remove as well, lmk

**Review by jasnonaz — APPROVED** [review]
Let's GO!

**Pull request merged**
