### PR TITLE
fix typo and re-format sql

### PR DESCRIPTION
**Pull request by Jstein77**
This PR fixes a typo and re-formats the example SQL.

### CODE REVIEW

**Comment by mirnawong1** [comment]
hey @Jstein77 - i switched the sql to lower case so match our [dbt sql style guide](https://docs.getdbt.com/best-practices/how-we-style/6-how-we-style-conclusion). the code is also looking a little weird [here](https://docs-getdbt-9f40o5rst-dbt-labs.vercel.app/docs/build/conversion#step-1-join-visits-and-buys) -- are you ok if i change it to lowercase and fix the formatting?

**Comment by Jstein77** [comment]
@mirnawong1 yes please! I wasn't aware we had a style guide for SQL snippets. I ran these through an auto-formatter to try and keep them consistent. Can you share the style guide for future PRs?

**Review by mirnawong1 — APPROVED** [review]

**Comment by mirnawong1** [comment]
no worries at all @Jstein77 ! i've changed this back to th dbt sql and folded in your typo fix 🙏 !  approved it and will merge!

this is the dbt style guide: https://docs.getdbt.com/best-practices/how-we-style/2-how-we-style-our-sql#basics for add'l info 🙏

**Comment by mirnawong1** [comment]
i'll try to see if this is something we can incorporate in our checks.

**Pull request merged**
