### PR TITLE
Remove old custom Link component

### PR DESCRIPTION
**Pull request by JKarlavige**
## What are you changing in this pull request and why?

[Asana task](https://app.asana.com/0/1200099998847559/1204175679335750/f)

This removes an old custom Link component which was causing issues with the [Assets feature](https://docusaurus.io/docs/markdown-features/assets#files) on Docusaurus. The issue is when links to assets (pdfs, documents) were clicked, it was not triggering a download.

The custom Link component was set to be used for all links on docs pages within `MDXComponents`. Today, Docusaurus uses their own `MDXA` component.

This adjusts the `MDXComponents` to use the built-in `MDXA` component for links on docs pages, which will resolve the assets issue and allow documents to be downloaded as expected.

## Preview

One area where the old Link component was being used was on the styles page. It was used within the `CodeBlock` component, as well as directly as a link on the page. We can confirm:
- `view the intro` codeblock link still works as expected
- the external `Links section` link under `Markdown Links` still works correctly.
 
https://deploy-preview-3000--docs-getdbt-com.netlify.app/styles

## Additional Notes

We have a separate PR (#3065) where we are fixing the broken links. That PR will merge into this PR once approved, then we will take this PR with the new component and all the fixed links live.

5/2/23 Update: #3065 has been approved and merged into this PR. The only original changed files for this PR are under `website/src`.

### CODE REVIEW

**Comment by matthewshaver** [comment]
https://www.notion.so/dbtlabs/Fixing-the-links-in-docs-72f9c4a8796f4724ba2b382c9e0ad8e6

**Comment by JKarlavige** [comment]
#3065 has been merged into this PR and is ready for review. This includes the old custom Link component removal. All the link fixes have been sorted out in #3065.

**Comment by john-rock** [comment]
The update functionality appears to be working on the styles page linked in the description. @JKarlavige do you want to resolve these conflicts before I approve?

**Comment by JKarlavige** [comment]
> The update functionality appears to be working on the styles page linked in the description. @JKarlavige do you want to resolve these conflicts before I approve?

Conflicts are sorted out and fixed a few more detected broken links!

**Review by john-rock — DISMISSED** [review]
lgtm :shipit:

**Comment by JKarlavige** [comment]
Hey @matthewshaver, i'll keep this PR open for you or someone on the docs team to look over before we take this live!

**Review by matthewshaver — APPROVED** [review]

**Review by matthewshaver — APPROVED** [review]

**Comment by matthewshaver** [comment]
@JKarlavige Looks good to me; let's ship it!

**Pull request merged**
