### PR TITLE
Update using-jinja.md

### PR DESCRIPTION
**Pull request by aruness**
Updated the get_payment_methods macro call

## Checklist

- [ ] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) so my content adheres to these guidelines.
- [ ] For [docs versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#about-versioning), review how to [version a whole page](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) and [version a block of content](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#versioning-blocks-of-content).
- [ ] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

Adding or removing pages (delete if not applicable):
- [ ] Add/remove page in `website/sidebars.js`
- [ ] Provide a unique filename for new pages
- [ ] Add an entry for deleted pages in `website/static/_redirects`
- [ ] Run link testing locally with `npm run build` to update the links that point to deleted pages

### CODE REVIEW

**Comment by mirnawong1** [comment]
hey @aruness , thanks for opening this pr up and great first contribution! i'd love to understand more on why you think we should add `(column_name, relation) %}` to the macro? from my understanding, the `{% macro get_payment_methods() %}` example is correct since it's meant to fetch payment methods from a particular relation using the `get_column_values` macro.

would love to hear your thoughts on this!

**Comment by aruness** [comment]
Oh, I get it, closing this PR. I apologize for my oversight.
________________________________

**Comment by aruness** [comment]
Closed, seems like an oversight from my end.

**Comment by mirnawong1** [comment]
no worries! thanks for opening this pr up and let us know if you have any questions!

**Pull request closed without merging**
