### PR TITLE
Added `catalog` to Databricks profile docs.

### PR DESCRIPTION
**Pull request by elongl**
Update Databrick’s profile definition according to the [new support](https://github.com/databricks/dbt-databricks#profile-setup) of Catalog selection.

## Prerelease docs
If this change is related to functionality in a prerelease version of dbt (delete if not applicable):
- [ ] I've added versioning components, as described in ["Versioning Docs"](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/versioningdocs.md)
- [ ] I've added a note to the prerelease version's [Migration Guide](https://github.com/dbt-labs/docs.getdbt.com/tree/current/website/docs/guides/migration/versions)

## Checklist
If you added new pages (delete if not applicable):
- [ ] The page has been added to `website/sidebars.js`
- [ ] The new page has a unique filename

If you removed existing pages (delete if not applicable):
- [ ] The page has been removed from `website/sidebars.js`
- [ ] An entry has been added to `_redirects`

### CODE REVIEW

**Review by dataders — COMMENTED** [review]
@elongl great addition. My only thought was that we add a little bit more information about Unity Catalog? perhaps as a Caveat? I imagine we'll see more UC-related support questions as time goes on.

**Comment by elongl** [comment]
@dataders Thanks for the feedback! I added a caveat as you requested. Let me know what you think.

**Comment by dataders** [comment]
@jtcohen6 @runleonarun do y'all think it's worthwhile to version block the unity catalog information? my gut tells me no, given that it's a rather essential feature moving forward. not sure how many folks will come to dbt-databricks in the future and want information only related to versions before `1.2.0`

**Comment by dataders** [comment]
@jtcohen6 @runleonarun do y'all think it's worthwhile to version block the unity catalog information? my gut tells me no, given that it's a rather essential feature moving forward. not sure how many folks will come to dbt-databricks in the future and want information only related to versions before `1.2.0`

**Comment by runleonarun** [comment]
@dataders I think calling out which version it's applicable to works just fine 👍🏻

**Review by dataders — APPROVED** [review]
thanks @elongl!

**Pull request merged**
