### PR TITLE
remove slack admin requirement/callout

### LINKED ISSUE #2967: Correct Slack Notification Note
### Contributions

- [X] I have read the contribution docs, and understand what's expected of me.

### What page(s) or areas on docs.getdbt.com are affected?

https://docs.getdbt.com/faqs/accounts/slack

### What changes are you suggesting?

You don't need to be an admin of the Slack workspace (cc: @christineberger) to configure Slack notifications - at least for unpaid Slack.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mirnawong1**
updating slack user change

Closes #2967

## Checklist

- [ ] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) and [About versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) so my content adheres to these guidelines.
- [ ] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

Adding new pages (delete if not applicable):
- [ ] Add page to `website/sidebars.js`
- [ ] Provide a unique filename for the new page

Removing or renaming existing pages (delete if not applicable):
- [ ] Remove page from `website/sidebars.js`
- [ ] Add an entry `_redirects`
- [ ] [Ran link testing](https://github.com/dbt-labs/docs.getdbt.com#running-the-cypress-tests-locally) to update the links that point to the deleted page

### CODE REVIEW

**Comment by mirnawong1** [comment]
cc @christineberger @epapineau

**Comment by b-per** [comment]
Are we sure that this is the case for all Slack plans?

**Comment by mirnawong1** [comment]
> Are we sure that this is the case for all Slack plans?

Yea it's a bit unclear, I'm wanting to confirm this with eng to get the specifications so it's more clear. I'll remove it from the review, Thank you @b-per 🙏

**Comment by mirnawong1** [comment]
closing pr to address at a later point when there is more clarity on which slack plans this applies to

**Pull request closed without merging**
