### PR TITLE
Update Python model docs for v1.3 release

### PR DESCRIPTION
**Pull request by jtcohen6**
missed in https://github.com/dbt-labs/docs.getdbt.com/pull/2196

### CODE REVIEW

**Review by runleonarun — APPROVED** [review]
LGTM! @jtcohen6 We're fixing the test failures here: https://github.com/dbt-labs/docs.getdbt.com/pull/2256

**Comment by jtcohen6** [comment]
@runleonarun Thanks for the quick look! I found one other broken link that I'll just quickly fix in this PR. Planning to announce v1.3 release to the community now, which is why I was giving the migration guide / new docs another quick look over.

**Comment by runleonarun** [comment]
> @runleonarun Thanks for the quick look! I found one other broken link that I'll just quickly fix in this PR. 

We fixed a million broken links. How can this be?

**Comment by jtcohen6** [comment]
Not sure, but I'm hoping this should do it? https://github.com/dbt-labs/docs.getdbt.com/pull/2255/commits/3000c3d213ab148d5ee0d4f1ed055868f43718cb

**Pull request merged**
