### PR TITLE
Update azuresynapse-profile.md

### PR DESCRIPTION
**Pull request by alieus**
Service Principal authentication instructions were incorrect.

## Pre-release docs
Is this change related to an unreleased version of dbt?
- [ ] Yes: please
    - update the base branch to `next`
    - add Changelog components: `<Changelog>[New/Changed] in v0.x.0</Changelog>`
    - add links to the "New and changed documentation" section of the latest [Migration Guide](../website/docs/docs/guides/migration-guide)
- [X] No: please ensure the base branch is `current`
- [ ] Unsure: we'll let you know!

### CODE REVIEW

**Comment by jtcohen6** [comment]
cc @swanderz

**Comment by dataders** [comment]
hey @jtcohen6 I caused @alieus grief with the incorrect documentation, so he's making this PR so no one has to suffer like he did. He already opened https://github.com/mikaelene/dbt-sqlserver/pull/58 to make the same change

**Comment by jtcohen6** [comment]
All good, just wanted to check! If this looks good to you, it looks good to me :)

**Review by clrcrl — APPROVED** [review]
As per @swanderz, this is a good PR

**Pull request merged**
