### PR TITLE
Fix: Remove release notes category

### PR DESCRIPTION
**Pull request by gwenwindflower**
## Description & motivation
It's causing 404s when clicked since no posts use this category yet

### CODE REVIEW

**Review by jasnonaz — APPROVED** [review]
Excellent thank you!

**Review by runleonarun — APPROVED** [review]
@gwenwindflower I see it's creating a bad link until we have content 😢  Thanks for catching this! I will re-add when I add a new release note blog.

**Comment by gwenwindflower** [comment]
we're getting the same error as @JKarlavige 's #1197 so waiting to see if somebody can get to the bottom of that

**Comment by gwenwindflower** [comment]
ah okay this error is just from the Add PR to Project Action, that is okay to fail for now. Merging and we'll figure that out!

**Pull request merged**
