### PR TITLE
Add information about defer & compile

### PR DESCRIPTION
**Pull request by siljamardla**
## What are you changing in this pull request and why?
Adding information about how defer and compile work together. 
Stumbled upon this functionality and decided to document it for the benefit of others.

### CODE REVIEW

**Comment by mirnawong1** [comment]
hey @siljamardla , thanks for opening this up! i'm going to work with the team internally with this and will revert back with more info! really appreciate your contributions ✨ !

**Comment by mirnawong1** [comment]
hey @siljamardla , can you provide more insight on your proposed changes?  Wondering if you're experiencing [this scenario](https://docs.getdbt.com/blog/defer-to-prod#other-things-to-to-know-about-defer) where you have dev artifacts that dbt is favoring?

**Comment by siljamardla** [comment]
> hey @siljamardla , can you provide more insight on your proposed changes? Wondering if you're experiencing [this scenario](https://docs.getdbt.com/blog/defer-to-prod#other-things-to-to-know-about-defer) where you have dev artifacts that dbt is favoring?

Will have to test again to be sure. But if you have tested and you're sure that defer also works with full compile, feel free to modify my PR. The main point is to make it known that defer also works with compile.

**Comment by siljamardla** [comment]
Hey @mirnawong1 
Tested again. 
- I dropped my dev schema
- I ran `dbt compile --defer --state target/live` (this is where I store the latest live manifest)
- Checked the compiled output. All the refs use my personal schema name. 
- I recreated my dev schema. I checked that there are no tables in it. 
- I ran `dbt compile --defer --state target/live` again
- Checked the compiled output, again all the refs use my personal schema name.
- I ran `dbt compile --defer --state target/live --select my_model_name > target/tmp_my_model_name.sql`
- Checked the output, in this one all the refs have been compiled to use the live schema names
- Just in case, I deleted my target folder and went through the same routine again, still the same outcome

Thus, I stand by the claim that defer does not work on `dbt compile`, but it does work when you compile something specific.

**Comment by siljamardla** [comment]
@mirnawong1, even if you plan to investigate and/or fix anything, I think it's valuable information that should be added to the docs meanwhile.

**Comment by mirnawong1** [comment]
Thanks so much @siljamardla ! Will take a look at this tomorrow and also would like to cc @dave-connors-3 as well!

**Comment by dave-connors-3** [comment]
@mirnawong1 @siljamardla hello there! i definitely believe this to be _unintended_ behavior, and should go through core support, and not land in the docs site until we get a bit more clarity into what's going on! 

@siljamardla, would you be willing to open up an issue on dbt-core, and document the steps you showed above? If i end up mistaken (which happens a whole lot!) we can come back here and update the docs accordingly

**Comment by mirnawong1** [comment]
hey @siljamardla , thank for your patience here! I've had a chat with @dave-connors-3 and this sounds like unintended behavior and possibly a bug. could you please [open a core issue](https://github.com/dbt-labs/dbt-core/issues/new?assignees=&labels=bug,triage&projects=&template=bug-report.yml&title=%5BBug%5D+%3Ctitle%3E) for the team to look at? 

appreciate your insight and looking forward to your future docs contributions ✨!  thank you as well @dave-connors-3 !

**Comment by mirnawong1** [comment]
i'll close this pr out and happy to reopen at a later point. thanks again!

**Comment by siljamardla** [comment]
As suggested, I've created an issue: 
https://github.com/dbt-labs/dbt-core/issues/9991

**Pull request closed without merging**
