### PR TITLE
Docs site is not versioning titles

### PR DESCRIPTION
**Pull request by JKarlavige**
## Description & motivation
Titles that are versioned, still show up in the right navigation TOC. This versions the TOC by checking against heading IDs on page.

Resolves Asana task: https://app.asana.com/0/1200099998847559/1202082721286478/f

## Pre-release docs
Is this change related to an unreleased version of dbt?
- [ ] Yes: please
    - update the base branch to `next`
    - add Changelog components: `<Changelog>[New/Changed] in v0.x.0</Changelog>`
    - add links to the "New and changed documentation" section of the latest [Migration Guide](../website/docs/docs/guides/migration-guide)
- [x] No: please ensure the base branch is `current`
- [ ] Unsure: we'll let you know!

## Preview
https://deploy-preview-1347--docs-getdbt-com.netlify.app/reference/resource-properties/tests

### CODE REVIEW

**Comment by JKarlavige** [comment]
Hey @runleonarun & @jtcohen6, this PR is for versioning the TOC items. I included the "Alternative format for defining tests" header from the `/reference/resource-properties/tests.md` file in a version block so we can test it here. That adjustment is currently building in the preview

**Review by lfracalossiFA — APPROVED** [review]
lgtm!

**Comment by runleonarun** [comment]
@JKarlavige this is great! One tiny thing, Jeremy had started a workaround that now shows up like this now that the versioning works properly:

Screen Shot 2022-04-19 at 9 40 18 AM

I think we need to search  for "Only supported by v1.1 or newer." and remove it and the second #heading if it's there.

**Comment by JKarlavige** [comment]
@runleonarun Updated the `/docs/reference/resource-properties/tests.md` and `/docs/reference/source-configs.md` files which had those statements, and moved titles into the VersionBlock components where possible.

**Review by runleonarun — APPROVED** [review]
LGTM!

**Pull request merged**
