### PR TITLE
Update to "Upgrading to 1.0.0"

### PR DESCRIPTION
**Pull request by leoebfolsom**
I corrected some minor errors in backtick (`) formatting, and added a missing period.

## Description & motivation
Having a fresh set of eyes, I noticed and corrected a couple of minor punctuation errors.

## Pre-release docs
Is this change related to an unreleased version of dbt?
- [ ] Yes: please
    - update the base branch to `next`
    - add Changelog components: `<Changelog>[New/Changed] in v0.x.0</Changelog>`
    - add links to the "New and changed documentation" section of the latest [Migration Guide](../website/docs/docs/guides/migration-guide)
- [x] No: please ensure the base branch is `current`
- [ ] Unsure: we'll let you know!

### CODE REVIEW

**Review by nghi-ly — DISMISSED** [review]
@leoebfolsom : tysm for catching and fixing those! really appreciate it! 

looks like you've got some merge conflicts. please let me know if you'd like my help with that!  i'll need access to your `leoebfolsom:patch-2` branch in order to help tho. i tried just now and couldn't check out your branch.

**Comment by leoebfolsom** [comment]
Thank you @nghi-ly, I'd love your help with those merge conflicts--I've added you as a collaborator. Please let me know if that works. Thank you!

**Comment by nghi-ly** [comment]
thank you @leoebfolsom ! looks like i can check out your branch now (yay! and thank you!) but i'm not retrieving the merge conflicts onto my local machine for some reason. i'll need to ask a teammate about this since running `git merge current` in your branch isn't behaving as i am expecting. apologies for the delay! i'll get back to this next week (we have Thanksgiving holiday in the USA).

**Comment by leoebfolsom** [comment]
@nghi-ly I'm also OOO for Thanksgiving, but if it's not resolved once I return, I'll try to help resolve those conflicts! Thanks! 🦃

**Comment by leoebfolsom** [comment]
@nghi-ly I think I figured it out (don't ask me exactly what I did!). I think git was being thrown off by the fact that the file I edited was moved to a different directory. I think the conflicts are now resolved, and all checks have passed!

**Review by runleonarun — APPROVED** [review]
LGTM!

**Pull request merged**
