### PR TITLE
Update connect-redshift-postgresql-alloydb.md

### PR DESCRIPTION
**Pull request by patkearns10**
## What are you changing in this pull request and why?

We have seen an uptick of redshift ssh tunnel tickets, so we would like to add this to the docs.

## Checklist

- [ ] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) and [About versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) so my content adheres to these guidelines.
- [ ] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

Adding new pages (delete if not applicable):
- [ ] Add page to `website/sidebars.js`
- [ ] Provide a unique filename for the new page

Removing or renaming existing pages (delete if not applicable):
- [ ] Remove page from `website/sidebars.js`
- [ ] Add an entry `website/static/_redirects`
- [ ] [Ran link testing](https://github.com/dbt-labs/docs.getdbt.com#running-the-cypress-tests-locally) to update the links that point to the deleted page

### CODE REVIEW

**Comment by mirnawong1** [comment]
hey @patkearns10 , let me know when you're ready to have this pr reviewed ✨

**Comment by patkearns10** [comment]
@mirnawong1 - I will let you know! We have two customer issues in process right now that might add a use-case to this!

**Comment by matthewshaver** [comment]
Hi @patkearns10 - This PR has been in draft for a number of months. Is this something we want to update and get reviewed/published or should it be closed?

**Comment by patkearns10** [comment]
Hi @matthewshaver  -- thank you so much for the reminder, I was awaiting a review from Scott, but obviously, he left! 
Should be good to go.

**Review by mirnawong1 — APPROVED** [review]
hey @patkearns10 ! thanks for opening this up and it looks great! approved and going to merge for you!

**Pull request merged**
