### PR TITLE
fix doris-setup id

### PR DESCRIPTION
**Pull request by johnblust**
## Description & motivation
Fixing `current` which is now broken due to an incorrect syntax

### CODE REVIEW

**Comment by lfracalossiFA** [comment]
Hi @johnblust ,
Is there a particular page I should be looking at, where the error occurred?

**Comment by johnblust** [comment]
> Hi @johnblust , Is there a particular page I should be looking at, where the error occurred?

Hey @lfracalossiFA, `website/docs/reference/warehouse-setups/doris-setup.md` had a capitalized "D" in the in the `id` field so the sidebar.js was breaking due to wrong syntax

**Comment by lfracalossiFA** [comment]
Ah, so as long as the sidebar isn't breaking, we're good. Got it. I'll take a peek.

**Review by lfracalossiFA — APPROVED** [review]
lgtm! 🚢

**Pull request merged**
