### PR TITLE
Add Demystifying Event Streams devblog

### PR DESCRIPTION
**Pull request by johnblust**
## Description & motivation

Add Charlie Summers devblog post on Event streams with dbt to the docs site. @reallocf #1894 

Set a temporary release date for now. Let me know when a good release date is!

### CODE REVIEW

**Comment by jasnonaz** [comment]
This is looking good thank you @johnblust! A few things to look into before we go live.

1. For some reason the text isn't getting pulled into the homepage 
image
@JKarlavige is there anything we need to do to make this flow through properly.

2. @johnblust could you share the code snippet for Charlie's team to use to canonicalize their post to the dev blog.

3. We'll want to update date for go-live. Perhaps thursday?

**Comment by JKarlavige** [comment]
@jasnonaz @johnblust The description on the homepage card is populated from the description property in the blog post markdown file. Filling out the description there should add it to the card!

image

**Comment by KiraFuruichi** [comment]
@jasnonaz since John is OOO this week, I updated the description, Charlie's author profile, and publish date for tomorrow. Lmk if the description works (I pulled it from the Coalesce talk 😆 ).

**Review by jasnonaz — APPROVED** [review]
Good to go!! Thank you @johnblust for loading and @KiraFuruichi for ironing out the final details!

**Pull request merged**
