### PR TITLE
Add Oracle and Materialize to trusted adapters lisst

### LINKED ISSUE #4034: Trust dbt-materialize
### Link to adapter repo

https://github.com/MaterializeInc/materialize/tree/main/misc/dbt-materialize

### Contact Details

marta@materialize.com, dennis@materialize.com

### Which of these best describes you?

I work for the vendor on top of which the dbt adapter functions

### Please agree to the each of the following

- [X] I am a maintainer of the adapter being submited for Trusted status
- [X] I have read both the [Trusted adapters](https://docs.getdbt.com/docs/trusted-adapters) and [Building a Trusted Adapter](https://docs.getdbt.com/guides/dbt-ecosystem/adapter-development/8-building-a-trusted-adapter) pages.
- [X] I believe that the adapter currently meets the expectations given above
- [X] I will ensure this adapter stays in compliance with the guidelines
- [X] I understand that dbt Labs reserves the right to remove an adapter from the trusted adapter list at any time, should any of the below guidelines not be met

### What icon should be used?

materialize-purple-mark

### LINKED ISSUE #4090: list dbt-oracle as trusted adapter
### Link to adapter repo

https://github.com/oracle/dbt-oracle

### Contact Details

abhishek.o.singh@oracle.com

### Which of these best describes you?

I work for the vendor on top of which the dbt adapter functions

### Please agree to the each of the following

- [X] I am a maintainer of the adapter being submited for Trusted status
- [X] I have read both the [Trusted adapters](https://docs.getdbt.com/docs/trusted-adapters) and [Building a Trusted Adapter](https://docs.getdbt.com/guides/dbt-ecosystem/adapter-development/8-building-a-trusted-adapter) pages.
- [X] I believe that the adapter currently meets the expectations given above
- [X] I will ensure this adapter stays in compliance with the guidelines
- [X] I understand that dbt Labs reserves the right to remove an adapter from the trusted adapter list at any time, should any of the below guidelines not be met

### What icon should be used?

_No response_

### PR DESCRIPTION
**Pull request by dataders**
## What are you changing in this pull request and why?

resolves: #4034
resolves: #4090 

These adapters are now trusted. updating docs site accordingly.

image

### CODE REVIEW

**Comment by dataders** [comment]
@morsapaes @dehume @aosingh seeking confirmation that I'm using the correct `.svg`

**Comment by dehume** [comment]
That looks correct. From our logo collection `materialize-purple-mark.svg`
materialize-purple-mark

**Review by mirnawong1 — APPROVED** [review]
lgtm @dataders (both in dark and light mode)!!

Screenshot 2023-10-03 at 09 34 52

**Comment by dataders** [comment]
@aosingh looking at [the new preview](https://docs-getdbt-com-git-moretrustedadapters-dbt-labs.vercel.app/docs/trusted-adapters#trusted-adapters), it seems the logo:
1. is not visible for light mode and
2. got smaller (as compared to the other `.svg` logos)
image
image

**Comment by aosingh** [comment]
@dataders this looks good. Thank you

**Pull request merged**
