### PR TITLE
Remove incorrect table qualification

### PR DESCRIPTION
**Pull request by pvonglehn**
Remove the qualification rtl because the table was not aliased to rtl in that section of the code

## Prerelease docs
If this change is related to functionality in a prerelease version of dbt (delete if not applicable):

## Checklist
If you added new pages (delete if not applicable):

If you removed existing pages (delete if not applicable):

### CODE REVIEW

**Comment by pvonglehn** [comment]
@runleonarun any idea why the checks are failing?

**Comment by pvonglehn** [comment]
@runleonarun @mirnawong1 Just seen this again after a long time. What needs to be done to get it merged?

**Comment by mirnawong1** [comment]
hi @pvonglehn, thank you so much for following up, and sincere apologies for the delay in getting this looked at. I'll get this looked at and merged for you ✨

**Review by mirnawong1 — APPROVED** [review]
🚢

**Pull request merged**
