### PR TITLE
Dbt oracle docs

### PR DESCRIPTION
**Pull request by dpavancini**
## Description & motivation
Added profile-oracle and oracle entry to supported databases file. I followed the format from Microsoft Server driver.

### CODE REVIEW

**Review by jtcohen6 — APPROVED** [review]
This looks great! Thanks for creating the plugin, and for adding to the docs site. (Sorry for the delay in reviewing.) Could you fix the file conflicts, and then I'll merge this in?

By the way, I see in the plugin readme that you implemented `dbt-integration-tests` + some additional custom testing. We are _nearly_ release-ready with a more comprehensive, flexible adapter testing suite: https://github.com/fishtown-analytics/dbt-adapter-tests. We'll push it to pypi when ready. I'd be happy to open an issue in the dbt-oracle repo with more details, if helpful.

**Comment by vitoravancini** [comment]
> This looks great! Thanks for creating the plugin, and for adding to the docs site. (Sorry for the delay in reviewing.) Could you fix the file conflicts, and then I'll merge this in?
> 
> By the way, I see in the plugin readme that you implemented `dbt-integration-tests` + some additional custom testing. We are _nearly_ release-ready with a more comprehensive, flexible adapter testing suite: https://github.com/fishtown-analytics/dbt-adapter-tests. We'll push it to pypi when ready. I'd be happy to open an issue in the dbt-oracle repo with more details, if helpful.

@jtcohen6 It would be very nice if you could open the issue for using the new adapter tests. I remember that the integration tests  used dbt_utils so I there a few test cases that I couldn't make it work without actually addign some code to dbt_utils.

**Review by jtcohen6 — COMMENTED** [review]
Thanks for fixing the merge conflicts. I'll open an issue in the `dbt-oracle` repo as soon as our testing suite is on pypi.

Two small procedural things that slipped my notice last week:
* Can you change the base branch of this PR from `master` to `current`?
* Can you add `reference/warehouse-profiles/profile-oracle` to [sidebars.js](https://github.com/fishtown-analytics/docs.getdbt.com/blob/current/website/sidebars.js#L423)?

**Comment by dpavancini** [comment]
> Thanks for fixing the merge conflicts. I'll open an issue in the `dbt-oracle` repo as soon as our testing suite is on pypi.
> 
> Two small procedural things that slipped my notice last week:
> 
> * Can you change the base branch of this PR from `master` to `current`?
> * Can you add `reference/warehouse-profiles/profile-oracle` to [sidebars.js](https://github.com/fishtown-analytics/docs.getdbt.com/blob/current/website/sidebars.js#L423)?

Done!

**Pull request merged**
