### PR TITLE
Community spotlight update

### PR DESCRIPTION
**Pull request by JKarlavige**
## What are you changing in this pull request and why?

[Asana](https://app.asana.com/0/1200099998847559/1202844016314455/f)

This adds the content for the initial Spotlight Members. The following additions for the community spotlight members were included:
- Adds the following fields:
  - Pronouns
  - Location
  - Organization
- Truncates `description` on spotlight index page
- Adjusts template to support new fields

## Previews
https://deploy-preview-3067--docs-getdbt-com.netlify.app
https://deploy-preview-3067--docs-getdbt-com.netlify.app/community/spotlight
https://deploy-preview-3067--docs-getdbt-com.netlify.app/community/spotlight/emily-riederer

### CODE REVIEW

**Comment by lfracalossiFA** [comment]
Hey @JKarlavige ,
I know you didn't ask me to review, but a couple of things I noticed:

- The second question [here](https://deploy-preview-3067--docs-getdbt-com.netlify.app/community/spotlight/emily-riederer) needs a question mark. 
- It looks like the "website" URL is malformed, and is coming out as "https://deploy-preview-3067--docs-getdbt-com.netlify.app/community/spotlight/emilyriederer.com"

**Comment by lfracalossiFA** [comment]
Also, I don't know if it's anything that matters or that we even have control over, but I notice these two warnings in the console:

Screenshot 2023-03-24 at 9 38 18 AM

It seems to be coming from `https://cdn.jsdelivr.net/npm/libraries/tracker-core/dist/index.module.js`, though, so I'm guessing that's a problem with the relevant npm package.

**Comment by JKarlavige** [comment]
> Hey @JKarlavige , I know you didn't ask me to review, but a couple of things I noticed:
> 
> * The second question [here](https://deploy-preview-3067--docs-getdbt-com.netlify.app/community/spotlight/emily-riederer) needs a question mark.
> * It looks like the "website" URL is malformed, and is coming out as "https://deploy-preview-3067--docs-getdbt-com.netlify.app/community/spotlight/emilyriederer.com"

Good call i'll get those adjusted! This is a WIP that will be sitting for awhile yet as we wait for spotlight member submissions to come in. I believe this will be going live around the first week of May.

**Review by john-rock — CHANGES_REQUESTED** [review]
Doesn't look like the file was changed in this PR but wanted to callout the lorem ipsum on the spotlight index page.
https://deploy-preview-3067--docs-getdbt-com.netlify.app/community/spotlight

image

**Comment by JKarlavige** [comment]
@john-rock Description in spotlight hero is updated, opening back up review

**Review by john-rock — DISMISSED** [review]
:shipit:

**Review by john-rock — APPROVED** [review]

**Pull request merged**
