### PR TITLE
Docusaurus v3

### PR DESCRIPTION
**Pull request by JKarlavige**
## What are you changing in this pull request and why?

Upgrades Docusaurus to latest version (3.4.0). This PR includes:
- Updating Docusaurus npm package and other required package updates
- Refactoring markdown files to work with MDX v3
- Reswizzling customized theme components to get latest versions of components
- Adjust MDX components as needed

[See full Docusaurus upgrade details here](https://docusaurus.io/docs/migration/v3)

## Previews

Verify cards correctly show `hoverSnippet` frontmatter property if set, and that the full description shows on the card:
- https://docs-getdbt-com-git-docusaurus-v3-dbt-labs.vercel.app/glossary

Verify page with `details` component loads without error:
- https://docs-getdbt-com-git-docusaurus-v3-dbt-labs.vercel.app/docs/supported-data-platforms

Verify trusted adapters page matches live site after removing `MSCallout` component which does not exist. This was added in PR #4874:
- https://docs-getdbt-com-git-docusaurus-v3-dbt-labs.vercel.app/docs/trusted-adapters

Fix import for `RowsAffected` snippet:
- https://docs-getdbt-com-git-docusaurus-v3-dbt-labs.vercel.app/reference/artifacts/run-results-json

Verify FAQs show at the bottom of this page:
- https://docs-getdbt-com-git-docusaurus-v3-dbt-labs.vercel.app/docs/build/sources

Verify snippets still work (first paragraph on the following page):
- https://docs-getdbt-com-git-docusaurus-v3-dbt-labs.vercel.app/docs/introduction

Verify built-in partials still work:
- https://docs-getdbt-com-git-docusaurus-v3-dbt-labs.vercel.app/docs/cloud/secure/about-privatelink

## TODO Before Merge
- [x] Fix/Merge in latest version of gsheets page, (`{props.type}`) was causing a build error
- [x] Fix FAQs not showing
- [x] Table formatting funky on [this page](https://docs-getdbt-com-git-docusaurus-v3-dbt-labs.vercel.app/docs/community-adapters)
- [x] [another funky table](https://docs-getdbt-com-git-docusaurus-v3-dbt-labs.vercel.app/docs/build/measures)
- [x] [funky table 3](https://docs-getdbt-com-git-docusaurus-v3-dbt-labs.vercel.app/docs/use-dbt-semantic-layer/sl-architecture)
- [x] [funky table 4](https://docs-getdbt-com-git-docusaurus-v3-dbt-labs.vercel.app/docs/dbt-versions/core)
- [x] banners are no longer present on EOL or Beta versions. They used to appear at the top of every page.
- [x] [release note asterisk not rendering](https://docs-getdbt-com-git-docusaurus-v3-dbt-labs.vercel.app/docs/dbt-versions/dbt-cloud-release-notes)
- [x] faq toggles not working on [this page](https://docs-getdbt-com-git-docusaurus-v3-dbt-labs.vercel.app/docs/deploy/ci-jobs#troubleshooting)
  - Looks like custom components now require capital-case. Renamed this component from `detailsToggle` to `DetailsToggle` and updated component usage on all pages.
  - Verify working on the following pages:
    - [mesh page](https://docs-getdbt-com-git-docusaurus-v3-dbt-labs.vercel.app/best-practices/how-we-mesh/mesh-5-faqs)
    - [about metricflow page](https://docs-getdbt-com-git-docusaurus-v3-dbt-labs.vercel.app/docs/build/about-metricflow)
    - [metricflow commands](https://docs-getdbt-com-git-docusaurus-v3-dbt-labs.vercel.app/docs/build/metricflow-commands)
    - [cloud cli installation](https://docs-getdbt-com-git-docusaurus-v3-dbt-labs.vercel.app/docs/cloud/cloud-cli-installation)
- [x] [faqs not toggling on this page](https://docs-getdbt-com-git-docusaurus-v3-dbt-labs.vercel.app/best-practices/how-we-mesh/mesh-5-faqs)
- [x] bring back markdown links in code blocks
  - [example 1](https://docs-getdbt-com-git-docusaurus-v3-dbt-labs.vercel.app/reference/resource-properties/columns)
  - [example 2](https://docs-getdbt-com-git-docusaurus-v3-dbt-labs.vercel.app/reference/dbt_project.yml)
  - [example 3](https://docs-getdbt-com-git-docusaurus-v3-dbt-labs.vercel.app/reference/resource-properties/freshness)

## Notes
Removed the `Snapshots/snapshot-target-schema` faq from the following pages,  as this faq does not exist and is empty on the live site:
  - [snapshots page](https://docs.getdbt.com/docs/build/snapshots)
  - [target_schema page](https://docs.getdbt.com/reference/resource-configs/target_schema)

With the upgrade, there are a number of warnings in the build logs for broken anchor links. MDX v3 improves the built-in linting. I sorted out all formatting errors causing build failures as part of this PR. I don't see these as a blocker to this PR, as they also exist on the live site. However, these warnings should still be cleaned up at some point. The docs team can now see these broken anchor links and sort out as needed. Example from the log below:
```
Broken anchor on source page path = /reference/resource-configs/spark-configs:
   -> linking to #databricks-setup (resolved as: /reference/resource-configs/spark-configs#databricks-setup)
```
Docusaurus provides a command to check for MDX formatting errors as well, which can help when writing content locally: `npx docusaurus-mdx-checker`

Removed the swizzled `CodeBlock` MDX component, which we customized (over 3 years ago) to support markdown links within code blocks. 

Removed the `FAQList` custom component as it was causing errors and is not used anywhere on the site.

An additional benefit with the upgrade is it looks like the build times improved. They now take ~3.5-4 minutes to complete, rather than 7-8 minutes.

### CODE REVIEW

**Comment by runleonarun** [comment]
JASON! This is so great. Thank you for taking this gritty project on for us!! Here's what I found so far:
* [This table](https://docs-getdbt-com-git-docusaurus-v3-dbt-labs.vercel.app/docs/community-adapters) looks funky

**Comment by john-rock** [comment]
Minor callout, it looks like the blog post titles on the dev blog index have their font size increased from 2rem to 3rem.

Live site on the left, preview on the right.
Developer_Blog___dbt_Developer_Hub_and_Developer_Blog___dbt_Developer_Hub

**Comment by john-rock** [comment]
The blog cards on the homepage look like they are missing their dates.
dbt_Developer_Hub

**Review by john-rock — CHANGES_REQUESTED** [review]
Went through a ton of pages. All is looking good aside from the two items I called out in comments above. Let me know if you have any questions on those.

**Comment by JKarlavige** [comment]
@john-rock Nice finds, both of these should now be fixed.

@runleonarun Is there anything else you and the team would like to check with this upgrade before we go live? If not, we can likely go live by tomorrow.

**Comment by runleonarun** [comment]
@JKarlavige It looks good to me! I will approve once I check with the team real quick...

**Comment by mirnawong1** [comment]
this looks good to me, thank you so very much @JKarlavige and @runleonarun !

**Review by runleonarun — APPROVED** [review]
🚢 it!

**Review by john-rock — APPROVED** [review]
lgtm!

**Comment by JKarlavige** [comment]
Thanks everyone for the review! I will ship it first thing tomorrow morning 🚀

**Review by matthewshaver — APPROVED** [review]

**Review by nghi-ly — APPROVED** [review]
lgtm! tysm!!  🙇‍♀️

**Pull request merged**
