### PR TITLE
update git token method

### PR DESCRIPTION
**Pull request by mirnawong1**
removed 'username' in the git token method via personal token. this is per [slack thread](https://getdbt.slack.com/archives/CMZ2V0X8V/p1675205181115869?thread_ts=1675103573.556199&cid=CMZ2V0X8V) and [internal slack thread](https://dbt-labs.slack.com/archives/CH1AWA9ST/p1675205465868879?thread_ts=1675204622.174259&cid=CH1AWA9ST)

cc @jeremyyeo @dave-connors-3 @schottj @joellabes 

## Checklist

- [ ] Review the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) and [About versioning](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) so my content adheres to these guidelines.
- [ ] Add a checklist item for anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

Adding new pages (delete if not applicable):
- [ ] Add page to `website/sidebars.js`
- [ ] Provide a unique filename for the new page

Removing or renaming existing pages (delete if not applicable):
- [ ] Remove page from `website/sidebars.js`
- [ ] Add an entry `_redirects`
- [ ] [Ran link testing](https://github.com/dbt-labs/docs.getdbt.com#running-the-cypress-tests-locally) to update the links that point to the deleted page

### CODE REVIEW

**Review by dave-connors-3 — APPROVED** [review]
LGTM -- would love one more approval to keep me honest :)

**Comment by mirnawong1** [comment]
> LGTM -- would love one more approval to keep me honest :)

cc @jeremyyeo @schottj @joellabes - can ya'll help us out pls?

**Review by schottj — APPROVED** [review]
perfect!

**Comment by joellabes** [comment]
Thank you @mirnawong1!!

**Pull request merged**
