### PR TITLE
Update docker.md

### PR DESCRIPTION
**Pull request by mirnawong1**
updated the github packages registry url to inform users where to find docker images. this is stemmed from the slack thread and user question here: https://dbt-labs.slack.com/archives/C017GDLAF7D/p1643882910072239 and community slack announcement here: https://getdbt.slack.com/archives/C37J8BQEL/p1643122331161800

please do let me know if you think it's appropriate to link the registry - many thanks

## Pre-release docs
Is this change related to an unreleased version of dbt?
- [ ] Yes: please
    - update the base branch to `next`
    - add Changelog components: `<Changelog>[New/Changed] in v0.x.0</Changelog>`
    - add links to the "New and changed documentation" section of the latest [Migration Guide](../website/docs/docs/guides/migration-guide)
- [x] No: please ensure the base branch is `current`
- [ ] Unsure: we'll let you know!

## Checklist
If you added new pages (delete if not applicable):
- [ ] The page has been added to `website/sidebars.js`
- [ ] The new page has a unique filename

If you removed existing pages (delete if not applicable):
- [ ] The page has been removed from `website/sidebars.js`
- [ ] An entry has been added to `_redirects`

### CODE REVIEW

**Comment by jtcohen6** [comment]
Thanks @mirnawong1!

I think we should wait for the fuller docs, coming in https://github.com/dbt-labs/docs.getdbt.com/pull/1051. My sense is those are nearly shipshape (cc @iknox-fa)

**Comment by mirnawong1** [comment]
hey @jtcohen6 no worries at all, i wasn't 100% sure if this was needed and just wanted to provide an interim link so happy to close this if thats cool! 👍

**Comment by jtcohen6** [comment]
Right on - not strictly opposed to merging in the interim, depending on how much more time we feel we need for the fuller docs

**Comment by jtcohen6** [comment]
Closing now that we've merged #1051

**Pull request closed without merging**
