### PR TITLE
Clarify that threads is optional and dbname alias

### PR DESCRIPTION
**Pull request by hlcianfagna**
Testing a minimal config with `dbt debug` I found `threads` to be optional and `database` to work as an alias for `dbname`

### CODE REVIEW

**Review by dataders — DISMISSED** [review]
thanks @hlcianfagna

**Comment by hlcianfagna** [comment]
> thanks @hlcianfagna

Apologies @dataders , I rebased the branch and it seems you would need to approve again.

**Review by dataders — APPROVED** [review]
:shipit:

**Comment by hlcianfagna** [comment]
Thanks again @dataders , now there are no conflicts, but it seems I do not have enough permissions to merge the PR.

**Pull request merged**
