### PR TITLE
teradata setup changes for dbt-cloud and python support

### PR DESCRIPTION
**Pull request by VarunSharma15**
## What are you changing in this pull request and why?

- Teradata is now supported on dbt-cloud, so the documentation was changed.
- Added the cloud-setup-callout snippet.
- Documentation of support for Python 3,12
- Updated Teradata-utils compatibility matrix 

## Checklist
- [ ] I have reviewed the [Content style guide](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/content-style-guide.md) so my content adheres to these guidelines.
- [ ] The topic I'm writing about is for specific dbt version(s) and I have versioned it according to the [version a whole page](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#adding-a-new-version) and/or [version a block of content](https://github.com/dbt-labs/docs.getdbt.com/blob/current/contributing/single-sourcing-content.md#versioning-blocks-of-content) guidelines.
- [ ] I have added checklist item(s) to this list for anything anything that needs to happen before this PR is merged, such as "needs technical review" or "change base branch."

### CODE REVIEW

**Comment by matthewshaver** [comment]
Thanks for opening this @VarunSharma15 We can't update this PR as we don't have access to the branch. Some of these changes have been made in another PR. Could you please update this to the latest so we can iron out any conflicts? Thank you!

**Comment by VarunSharma15** [comment]
Hi @matthewshaver 
Thank you for the response.
I could not find the other PR for Teradata setup page. 
If you don't mind can you please share the URL of that PR here, that would be helpful.

**Comment by mirnawong1** [comment]
hey @VarunSharma15 , i believe this is the pr Matt is referencing: https://github.com/dbt-labs/docs.getdbt.com/pull/6373/files

**Comment by VarunSharma15** [comment]
Thanks @mirnawong1 
I have resolved the conflict, but Vale linting workflow is failing, I couldn't find why
Can you please help me on that!

**Comment by mirnawong1** [comment]
hey @VarunSharma15 , thanks so much! i'll take a look and don't worry about the failed ci checks. Will sort it for you!

**Review by mirnawong1 — APPROVED** [review]
hey @VarunSharma15 thanks for your patience and for opening this up! great additions and i appreciate you taking the time to update this doc! looking forward to future contributions and merging this for you now ✨ !

**Comment by VarunSharma15** [comment]
Thank you @mirnawong1 !!  Appreciate the support 🙌

**Pull request merged**
