### PR TITLE
Update dbt-logo-full-white.png

### PR DESCRIPTION
**Pull request by amy-byrum**
Updated to new logo sans-underscore

### CODE REVIEW

**Comment by drewbanin** [comment]
FYI I had to patch the docusaurus CSS to prevent links from line-breaking in the nav bar. I think that with the new logo, that code isn't necessary anymore. Feel free to remove the css class below - it should serve to shift the nav links to the left a few pixels :)

https://github.com/fishtown-analytics/docs.getdbt.com/blob/d41e236e0408b6e54baeae040645d18c0d44222a/website/src/css/custom.css#L35-L37

**Comment by clrcrl** [comment]
One small thing — do we want to fuss with the horizontal alignment here? These are in fact center aligned, but for they feel off balance to me... I guess because "dbt" are bottom-heavy letters? Maybe I expect them to line up with the bottom of the letters? idk what my brain is doing haha. Anyway just a thought but not a blocker!

Screen Shot 2020-06-16 at 8 48 15 AM

**Comment by amy-byrum** [comment]
> One small thing — do we want to fuss with the horizontal alignment here? These are in fact center aligned, but for they feel off balance to me... I guess because "dbt" are bottom-heavy letters? Maybe I expect them to line up with the bottom of the letters? idk what my brain is doing haha. Anyway just a thought but not a blocker!
> 
> Screen Shot 2020-06-16 at 8 48 15 AM

Yes--it is due to the fact that the logo is bottom-heavy. Trick of the eyes! Adjusting the positioning is a fine way to help with that, but didn't do that here as it felt like a separate issue (i.e., this was the case even with the old logo, so for now I just focused on updating the asset). 

I have a few other things that are more pressing at the moment but I've got this on my todo list for later this week. Just to keep things straight I'll probably tackle the spacing issues on a new branch.

**Comment by clrcrl** [comment]
Perfect, let's merge this PR in!

**Pull request merged**
