### PR TITLE
Rearrange docs navbar; add dropdown for Learn and Community

### PR DESCRIPTION
**Pull request by lfracalossiFA**
## Description & motivation
Per [this Notion card](https://www.notion.so/fishtownanalytics/Research-Create-dropdown-menu-for-docs-navbar-f2b5c25bad4f4b5b952e73b08b3291b8), we would like to rearrange and simplify the primary navbar by consolidating "Learn" and "Community"-type links into two nav dropdowns.

## To-do before merge
Need input from @clrcrl on final verbiage.

## Pre-release docs
Is this change related to an unreleased version of dbt?
- [ ] Yes: please
- [x] No: please ensure the base branch is `current`
- [ ] Unsure: we'll let you know!

### CODE REVIEW

**Review by clrcrl — COMMENTED** [review]
I don't think the words here are quite right. To a new dbt user, what is the difference between "Tutorial" and "On Demand"? I can't land on better words though, @coapacetic , and thoughts?

**Comment by coapacetic** [comment]
hmmm yea, on demand doesn't make much sense here.  How about: Getting Started Tutorial, Online Courses, Live Courses?  I took a screenshot locally here: 

image

**Comment by clrcrl** [comment]
I like that, let's make that change and then we can 🚢

**Review by coapacetic — APPROVED** [review]
talked it our with @clrcrl - leggo! 🚢

**Review by clrcrl — APPROVED** [review]
:rocket:

**Comment by lfracalossiFA** [comment]
Thank you for getting this across the finish line, @coapacetic and @clrcrl ; I'm kind of a mess today.

**Pull request merged**
