### PR TITLE
Adding release note about how spotty internet issues no longer cause “IDE session timed out” message

### PR DESCRIPTION
**Pull request by runleonarun**
## Description & motivation

Adding new release note and Loom  describing how spotty internet issues don't cause the  “IDE session timed out” message.

## Pre-release docs
Is this change related to an unreleased version of dbt?
- [ ] Yes: please
    - update the base branch to `next`
    - add Changelog components: `<Changelog>[New/Changed] in v0.x.0</Changelog>`
    - add links to the "New and changed documentation" section of the latest [Migration Guide](../website/docs/docs/guides/migration-guide)
- [x] No: please ensure the base branch is `current`
- [ ] Unsure: we'll let you know!

## Checklist
If you added new pages (delete if not applicable):
- [ ] The page has been added to `website/sidebars.js`
- [ ] The new page has a unique filename

If you removed existing pages (delete if not applicable):
- [ ] The page has been removed from `website/sidebars.js`
- [ ] An entry has been added to `_redirects`

### CODE REVIEW

**Comment by runleonarun** [comment]
@schottj @davidharting Here's the PR for review!

**Comment by schottj** [comment]
LGTM!

**Review by schottj — APPROVED** [review]

**Review by joellabes — APPROVED** [review]
I find the duality of release notes _and_ product updates confusing - where should I look as a casual visitor? but leona tells me she's talked to @jasnonaz/@krevitt so I'm not going to re-litigate it!

**Comment by runleonarun** [comment]
> I find the duality of release notes and product updates confusing - where should I look as a casual visitor? but leona tells me she's talked to @jasnonaz/@krevitt so I'm not going to re-litigate it!

Yea maybe they remember what we had said exactly, but I think they felt like each served a separate purpose.

**Pull request merged**
