### PR TITLE
Replacing category-specific feeds w/ a global reverse-chronological blogroll

### PR DESCRIPTION
**Pull request by JKarlavige**
## Description & motivation
This replaces feature category-specific feeds on the dev blog homepage with a classic reverse-chronological blogroll.

## Pre-release docs
Is this change related to an unreleased version of dbt?
- [ ] Yes: please
    - update the base branch to `next`
    - add Changelog components: `<Changelog>[New/Changed] in v0.x.0</Changelog>`
    - add links to the "New and changed documentation" section of the latest [Migration Guide](../website/docs/docs/guides/migration-guide)
- [x] No: please ensure the base branch is `current`
- [ ] Unsure: we'll let you know!

## Preview
https://deploy-preview-1197--docs-getdbt-com.netlify.app/blog

### CODE REVIEW

**Comment by JKarlavige** [comment]
Hey @runleonarun, I noticed the `Add PR to project` GitHub action seems to be failing consistently on my PRs. Is that anything I should be concerned with, or should I be doing anything differently to get it to pass?

**Comment by JKarlavige** [comment]
@krevitt I added a `regular_posts_count` property to our `metadata.yml` file to control how how many recent posts to show.

**Review by krevitt — COMMENTED** [review]
Might this be filtering out any post where `is_featured = true` from the main blogroll, vs only the most recent n count of featured posts that are set to display (currently 4)?

Noticing the dateadd + union all posts aren't appearing in the blogroll.

**Comment by krevitt** [comment]
> @krevitt I added a `regular_posts_count` property to our `metadata.yml` file to control how how many recent posts to show.

Got it - and to confirm, we don't have pagination going anywhere in the dev blog right?

**Comment by JKarlavige** [comment]
> > @krevitt I added a `regular_posts_count` property to our `metadata.yml` file to control how how many recent posts to show.
> 
> Got it - and to confirm, we don't have pagination going anywhere in the dev blog right?

That's correct, no pagination at the moment. I can throw a discovery task into Asana to look into that.

**Comment by JKarlavige** [comment]
> Might this be filtering out any post where `is_featured = true` from the main blogroll, vs only the most recent n count of featured posts that are set to display (currently 4)?
> 
> Noticing the dateadd + union all posts aren't appearing in the blogroll.

I believe those are just missing the cut at 10 for the recent posts. They will be included once we can get pagination up and running. For the 'Recent Posts' section, i'm grabbing all posts without the featured: true, and all featured posts which aren't included in the feature section at the top

**Comment by krevitt** [comment]
> > Might this be filtering out any post where `is_featured = true` from the main blogroll, vs only the most recent n count of featured posts that are set to display (currently 4)?
> > Noticing the dateadd + union all posts aren't appearing in the blogroll.
> 
> I believe those are just missing the cut at 10 for the recent posts. They will be included once we can get pagination up and running. For the 'Recent Posts' section, i'm grabbing all posts without the featured: true, and all featured posts which aren't included in the feature section at the top

Thanks Jason - could we check "What's a Primary Key and Why Do We Test Them?" ([post link here](https://deploy-preview-1197--docs-getdbt-com.netlify.app/blog/primary-key-testing)) as one example?

Posted on 11/29 and is_featured = true, isn't appearing in either the featured posts section or the blogroll (which goes back to 9/15).

**Comment by JKarlavige** [comment]
Nice catch @krevitt, I redid the sorting to sort by date and then title. Also bumped the recent posts to show 15 rather than 10 until we get pagination setup, but feel free to adjust that to any amount.

**Review by lfracalossiFA — APPROVED** [review]
lgtm!

**Comment by runleonarun** [comment]
@JKarlavige sorry about that action failing. It's fixed now. I'm actually not sure how it ever worked. 🤷🏻

**Review by runleonarun — APPROVED** [review]
Looks MUCH better!

**Review by krevitt — APPROVED** [review]
Looks great, let's get this merged in!

**Pull request merged**
