### PR TITLE
Update snapshotting-freshness-for-one-source.md

### PR DESCRIPTION
**Pull request by jeremyholtzman**
I believe this is missing "source:" syntax

### CODE REVIEW

**Comment by jeremyholtzman** [comment]
Hey @runleonarun would you be able to review this? This is my first time contributing so if I'm missing anything please let me know :)

**Review by coapacetic — APPROVED** [review]
LGTM 🚀

**Review by runleonarun — APPROVED** [review]
This looks great @jeremyholtzman 

Did you do a search to see if we need to update the language elsewhere? Does this apply to all versions of dbt?

**Comment by jeremyholtzman** [comment]
@runleonarun good call, I just did a search and found other references which I just added. I also looked through our documentation and found that this only applies to v 0.21.0 and later according to https://docs.getdbt.com/reference/commands/source.

**Comment by runleonarun** [comment]
@jeremyholtzman Thanks for updating! Being that .20 is almost EOL I think it's OK to merge this PR without versioning the old syntax for .20. 

We can add a note similar to the one on the Source page:

>:::info As of dbt Core v0.21, you need to prefix sources with the `source:` selection method. In previous versions of dbt, sources were specified by name only. :::

**Comment by jeremyholtzman** [comment]
@runleonarun, sure thing, I just added the note you mentioned on both pages

**Review by runleonarun — APPROVED** [review]
🚢 it!

**Pull request merged**
